/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and build info */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["InviteCode"];
            };
            cookie?: never;
        };
        /**
         * Check an invite before signing up
         * @description Returns 404 if the invite doesn't exist, was used, or expired.
         */
        get: operations["getInvite"];
        put?: never;
        post?: never;
        /** Revoke an invite (admin) */
        delete: operations["deleteInvite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account with an invite and a password
         * @description Signs the new user in.
         */
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup/passkey/begin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start creating an account with an invite and a passkey
         * @description Returns WebAuthn creation options for `navigator.credentials.create`.
         *     The account is created when the ceremony finishes.
         */
        post: operations["beginPasskeySignup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup/passkey/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish creating an account with a passkey
         * @description Signs the new user in.
         */
        post: operations["finishPasskeySignup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with a username and password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkey/begin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start signing in with a passkey
         * @description Returns WebAuthn request options for `navigator.credentials.get`. No username needed.
         */
        post: operations["beginPasskeyLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkey/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish signing in with a passkey */
        post: operations["finishPasskeyLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out this session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update your profile */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set or change your password
         * @description `currentPassword` is required if you already have one. Other sessions
         *     are signed out.
         */
        put: operations["setPassword"];
        post?: never;
        /**
         * Remove your password (passkey-only sign-in)
         * @description Fails with 409 if you have no passkey.
         */
        delete: operations["deletePassword"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/passkeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your passkeys */
        get: operations["listPasskeys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/passkeys/begin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start adding a passkey */
        post: operations["beginAddPasskey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/passkeys/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish adding a passkey */
        post: operations["finishAddPasskey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/passkeys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Credential ID, base64url */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a passkey
         * @description Fails with 409 if it's your only way to sign in.
         */
        delete: operations["deletePasskey"];
        options?: never;
        head?: never;
        /** Rename a passkey */
        patch: operations["renamePasskey"];
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Everyone on this server */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All invites (admin) */
        get: operations["listInvites"];
        put?: never;
        /** Create an invite link (admin) */
        post: operations["createInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Services that can be linked */
        get: operations["listProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Your linked service accounts
         * @description Credentials are never returned.
         */
        get: operations["listLinks"];
        put?: never;
        /**
         * Link an account with a form (credentials providers)
         * @description Validates the fields with the service. Linking an account you've
         *     already linked updates that link.
         */
        post: operations["createLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/links/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Re-link with new credentials (credentials providers)
         * @description Must be the same account. Clears `needs_relink`.
         */
        put: operations["relink"];
        post?: never;
        /**
         * Unlink and delete the stored credentials
         * @description Queued tracks from this link stay in the queue but can't play.
         */
        delete: operations["unlink"];
        options?: never;
        head?: never;
        /**
         * Share a link with everyone, or stop sharing it
         * @description Only services whose `shareable` capability is set can be shared
         *     (`not_shareable` otherwise). Songs already queued from a link keep
         *     playing after it's unshared.
         */
        patch: operations["updateLink"];
        trace?: never;
    };
    "/pairings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start linking (or re-linking) by device pairing
         * @description For providers with `pairing` set. Show `userCode` and `verifyUrl`:
         *     the user opens the URL on any device and approves the code. Then poll
         *     `GET /pairings/{id}` every `interval` seconds until it's
         *     approved (`oauth2` providers continue with `POST /links/oauth` and
         *     `pairingId`) or linked (`device` providers).
         */
        post: operations["beginPairing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pairings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Whether a device pairing was approved
         * @description Asks the service at most once per `interval`. An expired, finished or
         *     unknown pairing is `pairing_expired`; a declined one is
         *     `service_rejected_credentials`.
         */
        get: operations["pollPairing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/links/oauth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start linking (or re-linking) an OAuth2 provider
         * @description Send the browser to `authUrl`. The service redirects back to
         *     `/api/links/oauth/callback`, which lands on the web app's
         *     `/settings/services` page. Providers with `pairing` set need their
         *     approved pairing first (`not_paired` otherwise).
         */
        post: operations["beginOAuthLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/links/oauth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OAuth2 redirect target (browser navigation)
         * @description Finishes linking and redirects to `/settings/services?linked=<link id>`,
         *     or `/settings/services?link_error=<error code>` on failure. Needs the
         *     session cookie, but always redirects rather than returning an error.
         */
        get: operations["completeOAuthLink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search every service you've linked, and shared ones
         * @description Searches each of your links, and every link someone has shared, at
         *     once for tracks, albums and artists.
         *     Each link's results come back as a group, in link order. A link that
         *     fails (offline, needs re-linking, too slow) gets a group with
         *     `error` set instead of failing the whole search.
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/links/{id}/albums/{albumId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                albumId: string;
            };
            cookie?: never;
        };
        /** An album and its tracks, through one of your links or a shared one */
        get: operations["getAlbum"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/links/{id}/artists/{artistId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                artistId: string;
            };
            cookie?: never;
        };
        /** An artist and their albums, through one of your links or a shared one */
        get: operations["getArtist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/links/{id}/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * The playlists of one of your links or a shared one
         * @description In the service's order. `not_found` if the service has no playlists (its `capabilities.playlists` is false).
         */
        get: operations["listPlaylists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/links/{id}/playlists/{playlistId}/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                playlistId: string;
            };
            cookie?: never;
        };
        /**
         * A page of a playlist's tracks, through one of your links or a shared one
         * @description In playlist order. A page can be short, or even empty, when the playlist holds things that can't be queued (podcast episodes, local files); keep going while there's a `next`.
         */
        get: operations["getPlaylistTracks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/links/{id}/artwork": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * An image from one of your links or a shared one
         * @description For `artwork` refs in search and browse results. Cacheable.
         */
        get: operations["getLinkArtwork"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{roomId}/queue": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        /**
         * The room's queue and its fair play order
         * @description The same snapshot `queue.updated` pushes over the room WebSocket.
         */
        get: operations["getQueue"];
        put?: never;
        /**
         * Add songs to the end of your lane
         * @description Each song is looked up on its service through one of your links, and
         *     its metadata is kept with the queue item. All are added, in order, or
         *     none are. When you add one song, services that can tell ahead of time
         *     that they won't play it (Spotify) are asked first, and the song is
         *     refused with `not_playable` and a message to show.
         *
         *     If the room has a repeat window (`fairness.repeatWindowMinutes`),
         *     songs already waiting or playing, or started within the window, are
         *     left out, matched by track or by ISRC across services. If that
         *     leaves nothing, the add is refused with `repeat` (409) and a
         *     message to show.
         */
        post: operations["addToQueue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{roomId}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        /**
         * Who played what, and the top tracks and artists
         * @description Sums up the songs that started in `[from, to)`, by default all of
         *     them. A session's recap is its stats: pass its `startedAt` and
         *     `endedAt` (plus a moment). Songs that failed or were removed don't
         *     count. Top tracks and artists count songs that played to the end.
         */
        get: operations["getRoomStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{roomId}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        /**
         * The room's listening sessions, newest first
         * @description A session is a stretch of listening: a new one starts when the
         *     room has been quiet for two hours.
         */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{roomId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        /**
         * Songs the room played, newest first
         * @description Songs that finished, were skipped or failed. The song playing now
         *     isn't included until it ends. Refetch on `nowplaying.updated` when
         *     the song changes. For the next page, pass the last item's
         *     `startedAt` as `before`.
         */
        get: operations["getHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{roomId}/queue/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: components["parameters"]["RoomId"];
                itemId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a queued song
         * @description Your own songs, or anyone's if you own the room. The playing song
         *     can't be removed (`not_queued`); skip it instead.
         */
        delete: operations["removeQueueItem"];
        options?: never;
        head?: never;
        /** Move one of your queued songs within your lane */
        patch: operations["moveQueueItem"];
        trace?: never;
    };
    "/rooms/{roomId}/queue/{itemId}/artwork": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: components["parameters"]["RoomId"];
                itemId: string;
            };
            cookie?: never;
        };
        /**
         * A queued song's artwork
         * @description Loaded through the link of whoever queued the song, so everyone in
         *     the room can see it. 404 if the song has none or its link is gone.
         */
        get: operations["getQueueItemArtwork"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every room */
        get: operations["listRooms"];
        put?: never;
        /** Create a room you own */
        post: operations["createRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{roomId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        /** A room */
        get: operations["getRoom"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change a room you own
         * @description Everyone in the room gets `room.updated`. A new fairness mode or
         *     `fairness` reorders the queue at once; `fairness` replaces the
         *     room's as a whole.
         */
        patch: operations["updateRoom"];
        trace?: never;
    };
    "/rooms/{roomId}/playback": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        /**
         * What the room is playing
         * @description The same state `nowplaying.updated` pushes over the room WebSocket.
         */
        get: operations["getPlayback"];
        put?: never;
        /**
         * Play, pause, skip, seek, or vote to skip
         * @description The room's `permissions` say who may do what (`forbidden`
         *     otherwise). The owner may do anything, and whoever queued a song
         *     may skip it. In a room whose skip permission is `vote`, everyone
         *     else sends `vote_skip` (and `unvote_skip` to take it back); the
         *     song is skipped once `skipVotes.needed` have voted.
         *     `play` needs a speaker (`no_player`); pausing, skipping, seeking or
         *     voting with nothing playing is `nothing_playing`.
         */
        post: operations["controlPlayback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{roomId}/player": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Become the room's speaker
         * @description The device takes over playback from any other speaker. If the room
         *     is idle and songs are waiting, the first one starts. Needs the
         *     room's `speaker` permission unless the device already is the
         *     speaker.
         */
        put: operations["claimPlayer"];
        post?: never;
        /**
         * Stop being the room's speaker
         * @description The song pauses. The speaker's user or the room's owner may do this.
         */
        delete: operations["releasePlayer"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{roomId}/player/report": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * The speaker reports on the song it's streaming
         * @description Send `playing` once audio starts, `progress` every few seconds,
         *     `paused` if playback stopped on its own, then `ended` or `error`.
         *     Only the speaker may report (`not_player`). Reports about a song
         *     that's no longer current are ignored; the reply is the current
         *     state either way.
         */
        post: operations["reportPlayback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{roomId}/stream/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: components["parameters"]["RoomId"];
                itemId: string;
            };
            cookie?: never;
        };
        /**
         * A song's audio
         * @description For the playing song, or a queued one to preload. Streamed from the
         *     song's service through the link of whoever queued it. Supports
         *     byte ranges when the service does. If the format isn't in `accept`
         *     it's transcoded (if the server can), and the result isn't seekable.
         */
        get: operations["streamQueueItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok";
            /** @example 0.1.0 */
            version: string;
        };
        Error: {
            /**
             * @description Stable, machine-readable error code.
             * @example invalid_credentials
             */
            code: string;
            /** @description Human-readable explanation. */
            message: string;
        };
        /** @enum {string} */
        Role: "admin" | "member";
        User: {
            id: string;
            username: string;
            displayName: string;
            /** @description Image URL. Absent means show initials on `color`. */
            avatar?: string;
            /**
             * @description Lane color, `#rrggbb`.
             * @example #7c3aed
             */
            color: string;
            role: components["schemas"]["Role"];
            /** Format: date-time */
            createdAt: string;
        };
        Me: components["schemas"]["User"] & {
            hasPassword: boolean;
            passkeyCount: number;
        };
        /** @description Fields to change. Send `avatar` as "" to remove it. */
        ProfileUpdate: {
            displayName?: string;
            avatar?: string;
            color?: string;
        };
        /** @description 2 to 32 characters: lowercase letters, digits, `.`, `_` and `-`. */
        Username: string;
        Password: string;
        SignupRequest: {
            invite: string;
            username: components["schemas"]["Username"];
            displayName: string;
            password: components["schemas"]["Password"];
        };
        PasskeySignupRequest: {
            invite: string;
            username: components["schemas"]["Username"];
            displayName: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        SetPasswordRequest: {
            currentPassword?: string;
            newPassword: components["schemas"]["Password"];
        };
        Ceremony: {
            /** @description Pass back to the matching finish endpoint within 5 minutes. */
            ceremonyId: string;
            /**
             * @description WebAuthn options as JSON (`publicKey` inside). Decode with
             *     `PublicKeyCredential.parseCreationOptionsFromJSON` or
             *     `parseRequestOptionsFromJSON`.
             */
            options: {
                [key: string]: unknown;
            };
        };
        FinishCeremony: {
            ceremonyId: string;
            /** @description The browser's `PublicKeyCredential.toJSON()`. */
            credential: {
                [key: string]: unknown;
            };
            /** @description Label for a new passkey, e.g. "Pixel 9". Optional. */
            name?: string;
        };
        Passkey: {
            /** @description Credential ID, base64url */
            id: string;
            name: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastUsedAt?: string;
        };
        InviteInfo: {
            role: components["schemas"]["Role"];
            /** Format: date-time */
            expiresAt: string;
        };
        Invite: {
            code: string;
            /** @description Link to share; opens the signup page. */
            url: string;
            role: components["schemas"]["Role"];
            createdBy?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
            usedBy?: string;
            /** Format: date-time */
            usedAt?: string;
        };
        CreateInviteRequest: {
            role?: components["schemas"]["Role"];
            /** @default 168 */
            expiresInHours: number;
        };
        ProviderInfo: {
            /** @example navidrome */
            id: string;
            name: string;
            icon: string;
            /** @enum {string} */
            playback: "stream" | "remote";
            /** @enum {string} */
            linkMethod: "credentials" | "oauth2" | "device";
            /**
             * @description Linking starts with a device pairing (`POST /pairings`):
             *     always for `device` providers, and before the redirect for
             *     `oauth2` providers that set it.
             */
            pairing: boolean;
            /** @description The form to show for `credentials` providers. Empty otherwise. */
            fields: components["schemas"]["LinkField"][];
            capabilities: {
                search: ("track" | "album" | "artist" | "playlist")[];
                playlists: boolean;
                artwork: boolean;
                lyrics: boolean;
                isrc: boolean;
                /** @description Links to this service can be shared with everyone on the server. */
                shareable: boolean;
            };
        };
        LinkField: {
            name: string;
            label: string;
            /**
             * @description `secret` fields must be masked.
             * @enum {string}
             */
            kind: "text" | "url" | "secret";
            required: boolean;
            placeholder?: string;
            help?: string;
        };
        ServiceLink: {
            id: string;
            /** @description The user who linked it. Not you when it's someone's shared link. */
            ownerId: string;
            provider: string;
            /** @example alice on music.example.com */
            accountLabel: string;
            /**
             * @description `needs_relink`: the service stopped accepting the credentials; link again.
             * @enum {string}
             */
            status: "ok" | "needs_relink" | "error";
            statusDetail?: string;
            /** @description Everyone on the server can search and queue from it. */
            shared: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastOkAt?: string;
        };
        CreateLinkRequest: {
            provider: string;
            fields: {
                [key: string]: string;
            };
        };
        ArtistCredit: {
            /** @description The artist's ID on the same link, if known. */
            id?: string;
            name: string;
        };
        AlbumCredit: {
            id?: string;
            title: string;
        };
        /** @description A track you can queue with `linkId` and `trackId`. */
        TrackResult: {
            linkId: string;
            provider: string;
            trackId: string;
            title: string;
            artists: components["schemas"]["ArtistCredit"][];
            album?: components["schemas"]["AlbumCredit"];
            /** Format: int64 */
            durationMs: number;
            explicit: boolean;
            /** @description Load with `/links/{linkId}/artwork?ref=`. */
            artwork?: string;
        };
        AlbumResult: {
            id: string;
            title: string;
            artists: components["schemas"]["ArtistCredit"][];
            year?: number;
            trackCount?: number;
            artwork?: string;
        };
        ArtistResult: {
            id: string;
            name: string;
            artwork?: string;
        };
        /** @description One link's search results. */
        SearchGroup: {
            linkId: string;
            /** @description Who linked it; someone else when it's a shared link. */
            ownerId: string;
            provider: string;
            accountLabel: string;
            tracks: components["schemas"]["TrackResult"][];
            albums: components["schemas"]["AlbumResult"][];
            artists: components["schemas"]["ArtistResult"][];
            error?: components["schemas"]["Error"];
        };
        SearchResults: {
            query: string;
            /** @description Empty if you have no links. */
            groups: components["schemas"]["SearchGroup"][];
        };
        AlbumDetail: {
            linkId: string;
            provider: string;
            album: components["schemas"]["AlbumResult"];
            /** @description In album order. */
            tracks: components["schemas"]["TrackResult"][];
        };
        ArtistDetail: {
            linkId: string;
            provider: string;
            artist: components["schemas"]["ArtistResult"];
            albums: components["schemas"]["AlbumResult"][];
        };
        PlaylistResult: {
            id: string;
            name: string;
            /** @description The owner's username on the service. */
            owner?: string;
            trackCount?: number;
            artwork?: string;
        };
        PlaylistList: {
            linkId: string;
            provider: string;
            playlists: components["schemas"]["PlaylistResult"][];
            /** @description Cursor for the next page; absent on the last. */
            next?: string;
        };
        PlaylistTracks: {
            linkId: string;
            provider: string;
            tracks: components["schemas"]["TrackResult"][];
            /** @description Cursor for the next page; absent on the last. */
            next?: string;
        };
        AddToQueueRequest: {
            items: components["schemas"]["TrackToQueue"][];
        };
        /**
         * @description A song from search (`linkId` and `trackId`), or a song the room
         *     already had, again (`fromItemId`). Queueing again from someone
         *     else's service needs the room's `matching.borrow`
         *     (`cant_borrow` otherwise).
         */
        TrackToQueue: {
            /** @description A link you can use (yours, or shared). */
            linkId?: string;
            /** @description The track's ID on that service, from search. */
            trackId?: string;
            /** @description One of the room's queue items, from history or stats. */
            fromItemId?: string;
        };
        MoveQueueItemRequest: {
            /** @description Where in your lane to put the song; 0 is the front. Past the end means the end. */
            position: number;
        };
        UpdateLinkRequest: {
            shared: boolean;
        };
        RelinkRequest: {
            fields: {
                [key: string]: string;
            };
        };
        /**
         * @description Set `provider` to link a new account, or `linkId` to re-link one. For
         *     providers that pair first, set only `pairingId`, the approved pairing.
         */
        BeginOAuthLinkRequest: {
            provider?: string;
            linkId?: string;
            pairingId?: string;
        };
        /** @description Set `provider` to link a new account, or `linkId` to re-link one. */
        BeginPairingRequest: {
            provider?: string;
            linkId?: string;
        };
        Pairing: {
            id: string;
            /** @description Where to approve, with the code filled in when the service allows. */
            verifyUrl: string;
            userCode: string;
            /** @description Seconds between polls. */
            interval: number;
            /** Format: date-time */
            expiresAt: string;
        };
        PairingStatus: {
            /**
             * @description `approved`: continue with `POST /links/oauth` and `pairingId`.
             *     `linked`: done; `link` is set.
             * @enum {string}
             */
            status: "pending" | "approved" | "linked";
            link?: components["schemas"]["ServiceLink"];
        };
        /**
         * @description A message on the room WebSocket, `GET /ws/rooms/{roomId}?since=<version>`.
         *     The socket needs the session cookie and is server-push only: send
         *     changes over the REST API.
         *
         *     `data` by `type`:
         *     - `hello`: RoomHello. Always first.
         *     - `queue.updated`: QueueSnapshot. Sent after hello unless `since`
         *       equals the current version, then on every change.
         *     - `nowplaying.updated`: NowPlaying. Sent after hello, then on change.
         *     - `playback.notice`: PlaybackNotice. Something to tell members, like
         *       a song skipped because it couldn't play.
         *     - `member.joined`, `member.left`: User. Someone's first connection to
         *       the room opened, or their last one closed.
         *     - `link.status`: ServiceLink. One of your links changed status.
         *     - `room.updated`: Room. The room's name or settings changed.
         *
         *     Close code 1013 (try again later) means the client fell behind and
         *     missed events: reconnect with `since` set to the last version seen.
         *     Close code 4001 means the session ended; sign in again.
         */
        RoomEvent: {
            /** @enum {string} */
            type: "hello" | "queue.updated" | "nowplaying.updated" | "playback.notice" | "member.joined" | "member.left" | "link.status" | "room.updated";
            /**
             * Format: int64
             * @description Queue version, on `queue.updated` only.
             */
            version?: number;
            data: Record<string, never>;
        };
        RoomHello: {
            roomId: string;
            roomName: string;
            /** @description Your user ID. */
            you: string;
            /** @description Everyone connected to the room right now, you included. */
            members: components["schemas"]["User"][];
        };
        QueueSnapshot: {
            roomId: string;
            /** Format: int64 */
            version: number;
            /**
             * @description The playing item and everything queued, grouped by who added it,
             *     each lane in order.
             */
            items: components["schemas"]["QueueItem"][];
            /**
             * @description IDs of the queued items in the order they will play, as the room's
             *     fairness mode interleaves the lanes. The playing item isn't included.
             */
            upNext: string[];
        };
        QueueItem: {
            id: string;
            /** @description User ID. */
            addedBy: string;
            /** @enum {string} */
            state: "queued" | "playing" | "played" | "skipped" | "removed";
            /** Format: int64 */
            lanePosition: number;
            /** Format: date-time */
            addedAt: string;
            track: components["schemas"]["QueuedTrack"];
            via?: components["schemas"]["PlaysVia"];
        };
        /**
         * @description Where the song plays from instead of its own service, which
         *     couldn't play it: the same recording, found on another service in
         *     the room. Show "playing from Navidrome instead of Spotify".
         */
        PlaysVia: {
            provider: string;
            linkId: string;
            trackId: string;
        };
        PlayedItem: {
            item: components["schemas"]["QueueItem"];
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endedAt: string;
            /** @enum {string} */
            endReason: "finished" | "skipped" | "removed" | "error";
        };
        RoomStats: {
            /** @description Songs that played, to the end or until skipped. */
            plays: number;
            skipped: number;
            /** Format: int64 */
            listeningMs: number;
            topTracks: components["schemas"]["TrackCount"][];
            topArtists: components["schemas"]["ArtistCount"][];
            /** @description Everyone whose songs played, most plays first. */
            people: components["schemas"]["PersonStats"][];
            first?: components["schemas"]["PlayedItem"];
            last?: components["schemas"]["PlayedItem"];
        };
        /** @description One person's songs, whoever skipped them. */
        PersonStats: {
            userId: string;
            plays: number;
            skipped: number;
            /** Format: int64 */
            listeningMs: number;
            topTracks: components["schemas"]["TrackCount"][];
            topArtists: components["schemas"]["ArtistCount"][];
        };
        /** @description A song and how many times it played to the end. `item` is its latest play. */
        TrackCount: {
            item: components["schemas"]["QueueItem"];
            plays: number;
        };
        ArtistCount: {
            name: string;
            plays: number;
        };
        ListeningSession: {
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endedAt: string;
            plays: number;
            /** @description User IDs whose songs played, most first. */
            people: string[];
        };
        /** @description The track as it was when queued; still shown if its service is offline. */
        QueuedTrack: {
            provider: string;
            /** @description Absent if the link was removed; the track can't play then. */
            linkId?: string;
            trackId: string;
            title: string;
            artists: string[];
            /**
             * @description The provider's ID for each of `artists`, in the same order, within
             *     `linkId`. Empty where the provider didn't say.
             */
            artistIds?: string[];
            album?: string;
            /** @description The provider's album ID within `linkId`, if known. */
            albumId?: string;
            /** Format: int64 */
            durationMs: number;
            explicit: boolean;
            artwork?: string;
        };
        /**
         * @description A room's playback, as the server sees it. While `playing`, the
         *     position is `positionMs` at `at` and advances with the clock.
         */
        NowPlaying: {
            roomId: string;
            state: components["schemas"]["PlaybackState"];
            item?: components["schemas"]["QueueItem"];
            /**
             * @description How `item` plays. `stream`: the speaker plays it from
             *     `/rooms/{roomId}/stream/{itemId}`. `remote`: the song's service
             *     plays it on its own device, and the speaker just shows it.
             * @enum {string}
             */
            driver?: "stream" | "remote";
            /** Format: int64 */
            positionMs: number;
            /**
             * Format: date-time
             * @description Server time `positionMs` was true at.
             */
            at: string;
            /**
             * Format: int64
             * @description Increases whenever the speaker must act: a new song, play,
             *     pause, or seek. Apply each revision once.
             */
            revision: number;
            player?: components["schemas"]["Player"];
            next?: components["schemas"]["QueueItem"];
            skipVotes?: components["schemas"]["SkipVotes"];
        };
        /**
         * @description The vote to skip the playing song, while the room's skip permission
         *     is `vote`. Everyone in the room but whoever queued the song can
         *     vote; `needed` changes as people come and go.
         */
        SkipVotes: {
            /** @description IDs of the users who voted, in order. */
            voters: string[];
            /** @description How many votes skip the song. */
            needed: number;
        };
        /**
         * @description `idle`: nothing to play, or no speaker. `loading`: waiting for the
         *     speaker to start the song.
         * @enum {string}
         */
        PlaybackState: "idle" | "loading" | "playing" | "paused";
        /** @description The device a room plays through. */
        Player: {
            deviceId: string;
            userId: string;
            name: string;
            /** Format: date-time */
            lastSeen: string;
        };
        PlaybackCommand: {
            /** @enum {string} */
            action: "play" | "pause" | "skip" | "seek" | "vote_skip" | "unvote_skip";
            /**
             * Format: int64
             * @description Where to seek to.
             */
            positionMs?: number;
            /**
             * @description Skip (or vote) only if this is still the current song, so two
             *     people tapping skip skip one song.
             */
            itemId?: string;
        };
        ClaimPlayerRequest: {
            /** @description A stable ID the device makes up and keeps. */
            deviceId: string;
            /** @example Collin's phone */
            name: string;
        };
        PlayerReport: {
            deviceId: string;
            itemId: string;
            /** @enum {string} */
            event: "playing" | "progress" | "paused" | "ended" | "error";
            /** Format: int64 */
            positionMs: number;
            /** @description What went wrong, for `error`. */
            error?: string;
        };
        /** @description Something members should hear about, like a song skipped because its service failed. */
        PlaybackNotice: {
            roomId: string;
            itemId?: string;
            message: string;
        };
        /** @enum {string} */
        FairnessMode: "round_robin" | "fifo";
        /**
         * @description Who may do something. The room's owner always may.
         * @enum {string}
         */
        PermissionLevel: "everyone" | "owner";
        /**
         * @description Who may skip. `vote`: the owner may, and everyone else votes (see
         *     SkipVotes). Whoever queued a song may always skip it.
         * @enum {string}
         */
        SkipPermission: "everyone" | "vote" | "owner";
        RoomPermissions: {
            playPause: components["schemas"]["PermissionLevel"];
            seek: components["schemas"]["PermissionLevel"];
            skip: components["schemas"]["SkipPermission"];
            speaker: components["schemas"]["PermissionLevel"];
        };
        /** @description Permissions to change. Missing ones stay as they are (`everyone` for a new room). */
        RoomPermissionsChange: {
            playPause?: components["schemas"]["PermissionLevel"];
            seek?: components["schemas"]["PermissionLevel"];
            skip?: components["schemas"]["SkipPermission"];
            speaker?: components["schemas"]["PermissionLevel"];
        };
        /**
         * @description A skip vote passes once more than this percent of the room has
         *     voted (not counting whoever queued the song): 50 is a majority.
         * @default 50
         */
        SkipVotePercent: number;
        /**
         * @description Tunes the room's fairness mode. While someone else has songs
         *     waiting, nobody gets more than `maxInARow` songs in a row, and
         *     `cooldown` other songs play between one person's songs; when
         *     nobody else is waiting, the music keeps going anyway. In round
         *     robin, `weights` give some people more songs per turn.
         */
        RoomFairness: {
            /** @description 0 is no cap. */
            maxInARow: number;
            /** @description Songs by others between one person's songs. 0 is none. */
            cooldown: number;
            /** @description Songs per turn (2 to 4) by user ID, in round robin. Everyone else gets 1. */
            weights: {
                [key: string]: number;
            };
            /**
             * @description Refuse songs already waiting or playing, or started within this
             *     many minutes. 0 is off.
             */
            repeatWindowMinutes: number;
        };
        /** @description How the room uses the same song on other services. */
        RoomMatching: {
            /**
             * @description When a song's service can't play it, play the same recording
             *     from another service in the room: a service of someone who's
             *     here, or a shared one. Matched by ISRC, or carefully by title,
             *     artist and length.
             * @default true
             */
            fallback: boolean;
            /**
             * @description Anyone may queue a song the room played again, even if it's only
             *     on someone else's service.
             * @default false
             */
            borrow: boolean;
        };
        Room: {
            id: string;
            name: string;
            ownerId: string;
            fairnessMode: components["schemas"]["FairnessMode"];
            fairness: components["schemas"]["RoomFairness"];
            matching: components["schemas"]["RoomMatching"];
            permissions: components["schemas"]["RoomPermissions"];
            skipVotePercent: components["schemas"]["SkipVotePercent"];
            /** Format: date-time */
            createdAt: string;
        };
        CreateRoomRequest: {
            name: string;
            fairnessMode?: components["schemas"]["FairnessMode"];
            fairness?: components["schemas"]["RoomFairness"];
            matching?: components["schemas"]["RoomMatching"];
            permissions?: components["schemas"]["RoomPermissionsChange"];
            skipVotePercent?: components["schemas"]["SkipVotePercent"];
        };
        UpdateRoomRequest: {
            name?: string;
            fairnessMode?: components["schemas"]["FairnessMode"];
            fairness?: components["schemas"]["RoomFairness"];
            matching?: components["schemas"]["RoomMatching"];
            permissions?: components["schemas"]["RoomPermissionsChange"];
            skipVotePercent?: components["schemas"]["SkipVotePercent"];
        };
    };
    responses: {
        /**
         * @description An error. Common statuses: 400 invalid input, 401 not signed in or
         *     wrong credentials, 403 not allowed, 404 not found, 409 conflict,
         *     429 too many attempts (see Retry-After).
         */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Signed in; the session cookie is set */
        SignedIn: {
            headers: {
                "Set-Cookie"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Me"];
            };
        };
        /** @description A WebAuthn ceremony to complete in the browser */
        Ceremony: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Ceremony"];
            };
        };
    };
    parameters: {
        InviteCode: string;
        RoomId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["InviteCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The invite can be used */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteInfo"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["InviteCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            201: components["responses"]["SignedIn"];
            default: components["responses"]["Error"];
        };
    };
    beginPasskeySignup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasskeySignupRequest"];
            };
        };
        responses: {
            200: components["responses"]["Ceremony"];
            default: components["responses"]["Error"];
        };
    };
    finishPasskeySignup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinishCeremony"];
            };
        };
        responses: {
            201: components["responses"]["SignedIn"];
            default: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: components["responses"]["SignedIn"];
            default: components["responses"]["Error"];
        };
    };
    beginPasskeyLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ceremony"];
            default: components["responses"]["Error"];
        };
    };
    finishPasskeyLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinishCeremony"];
            };
        };
        responses: {
            200: components["responses"]["SignedIn"];
            default: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out; the session cookie is cleared */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description The updated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    setPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPasswordRequest"];
            };
        };
        responses: {
            /** @description Password set */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    deletePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Password removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listPasskeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Passkeys, oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Passkey"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    beginAddPasskey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ceremony"];
            default: components["responses"]["Error"];
        };
    };
    finishAddPasskey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinishCeremony"];
            };
        };
        responses: {
            /** @description The new passkey */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Passkey"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deletePasskey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Credential ID, base64url */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    renamePasskey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Credential ID, base64url */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Renamed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Users, oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listInvites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invites, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invite"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInviteRequest"];
            };
        };
        responses: {
            /** @description The new invite */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invite"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Providers, in registration order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderInfo"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listLinks: {
        parameters: {
            query?: {
                /** @description `shared`: also list links others have shared, after yours. */
                include?: "shared";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Links, oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceLink"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLinkRequest"];
            };
        };
        responses: {
            /** @description The link */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceLink"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    relink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelinkRequest"];
            };
        };
        responses: {
            /** @description The link */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceLink"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    unlink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unlinked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updateLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLinkRequest"];
            };
        };
        responses: {
            /** @description The link */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceLink"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    beginPairing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BeginPairingRequest"];
            };
        };
        responses: {
            /** @description The pairing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pairing"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    pollPairing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The pairing's status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairingStatus"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    beginOAuthLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BeginOAuthLinkRequest"];
            };
        };
        responses: {
            /** @description Where to send the browser */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        authUrl: string;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    completeOAuthLink: {
        parameters: {
            query?: {
                state?: string;
                code?: string;
                /** @description Set by the service when the user declined. */
                error?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Back to the web app */
            303: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    search: {
        parameters: {
            query: {
                q: string;
                /** @description Most results per kind, per link. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Results, one group per link */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResults"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getAlbum: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                albumId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The album */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumDetail"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getArtist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                artistId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The artist */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistDetail"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listPlaylists: {
        parameters: {
            query?: {
                /** @description The previous page's `next`. */
                cursor?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of playlists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getPlaylistTracks: {
        parameters: {
            query?: {
                /** @description The previous page's `next`. */
                cursor?: string;
            };
            header?: never;
            path: {
                id: string;
                playlistId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of tracks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistTracks"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getLinkArtwork: {
        parameters: {
            query: {
                ref: string;
                /** @description Wanted width in pixels; a hint. */
                size?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/*": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getQueue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The queue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueSnapshot"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    addToQueue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddToQueueRequest"];
            };
        };
        responses: {
            /** @description The queue after the change */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueSnapshot"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getRoomStats: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path: {
                roomId: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomStats"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listSessions: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                roomId: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListeningSession"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getHistory: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Only plays that started before this time. */
                before?: string;
                /** @description Only this person's songs. */
                userId?: string;
            };
            header?: never;
            path: {
                roomId: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent plays */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayedItem"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    removeQueueItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: components["parameters"]["RoomId"];
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The queue after the change */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueSnapshot"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    moveQueueItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: components["parameters"]["RoomId"];
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveQueueItemRequest"];
            };
        };
        responses: {
            /** @description The queue after the change */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueSnapshot"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getQueueItemArtwork: {
        parameters: {
            query?: {
                /** @description Wanted width in pixels; a hint. */
                size?: number;
            };
            header?: never;
            path: {
                roomId: components["parameters"]["RoomId"];
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/*": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listRooms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rooms, oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Room"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoomRequest"];
            };
        };
        responses: {
            /** @description The new room */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Room"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The room */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Room"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoomRequest"];
            };
        };
        responses: {
            /** @description The room after the change */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Room"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getPlayback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The playback state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NowPlaying"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    controlPlayback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaybackCommand"];
            };
        };
        responses: {
            /** @description The playback state after the command */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NowPlaying"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    claimPlayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimPlayerRequest"];
            };
        };
        responses: {
            /** @description The playback state with this device as the speaker */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NowPlaying"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    releasePlayer: {
        parameters: {
            query: {
                deviceId: string;
            };
            header?: never;
            path: {
                roomId: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The playback state without a speaker */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NowPlaying"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    reportPlayback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: components["parameters"]["RoomId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerReport"];
            };
        };
        responses: {
            /** @description The current playback state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NowPlaying"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    streamQueueItem: {
        parameters: {
            query?: {
                /** @description Comma-separated content types the player can decode, e.g. `audio/mpeg,audio/aac,audio/flac`. Empty means any. */
                accept?: string;
                /** @description Bitrate cap in kbit/s, for services or transcodes that can lower it. */
                maxBitrate?: number;
            };
            header?: {
                /** @example bytes=0- */
                Range?: string;
            };
            path: {
                roomId: components["parameters"]["RoomId"];
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The whole song */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/*": string;
                };
            };
            /** @description Part of the song (see Content-Range) */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/*": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
