// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: avatars.sql

package store

import (
	"context"
	"time"
)

const deleteAvatar = `-- name: DeleteAvatar :exec
DELETE FROM avatars WHERE user_id = ?
`

func (q *Queries) DeleteAvatar(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteAvatar, userID)
	return err
}

const getAvatar = `-- name: GetAvatar :one
SELECT user_id, data, content_type, updated_at FROM avatars WHERE user_id = ?
`

func (q *Queries) GetAvatar(ctx context.Context, userID string) (Avatar, error) {
	row := q.db.QueryRowContext(ctx, getAvatar, userID)
	var i Avatar
	err := row.Scan(
		&i.UserID,
		&i.Data,
		&i.ContentType,
		&i.UpdatedAt,
	)
	return i, err
}

const putAvatar = `-- name: PutAvatar :exec
INSERT INTO avatars (user_id, data, content_type, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (user_id) DO UPDATE SET data = excluded.data, content_type = excluded.content_type, updated_at = excluded.updated_at
`

type PutAvatarParams struct {
	UserID      string
	Data        []byte
	ContentType string
	UpdatedAt   time.Time
}

func (q *Queries) PutAvatar(ctx context.Context, arg PutAvatarParams) error {
	_, err := q.db.ExecContext(ctx, putAvatar,
		arg.UserID,
		arg.Data,
		arg.ContentType,
		arg.UpdatedAt,
	)
	return err
}
