// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: beat_maps.sql

package store

import (
	"context"
	"time"
)

const getBeatMap = `-- name: GetBeatMap :one
SELECT provider, track_id, version, found, map, analyzed_at, used_at FROM beat_maps WHERE provider = ? AND track_id = ?
`

type GetBeatMapParams struct {
	Provider string
	TrackID  string
}

func (q *Queries) GetBeatMap(ctx context.Context, arg GetBeatMapParams) (BeatMap, error) {
	row := q.db.QueryRowContext(ctx, getBeatMap, arg.Provider, arg.TrackID)
	var i BeatMap
	err := row.Scan(
		&i.Provider,
		&i.TrackID,
		&i.Version,
		&i.Found,
		&i.Map,
		&i.AnalyzedAt,
		&i.UsedAt,
	)
	return i, err
}

const putBeatMap = `-- name: PutBeatMap :exec
INSERT INTO beat_maps (provider, track_id, version, found, map, analyzed_at, used_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (provider, track_id) DO UPDATE SET
    version = excluded.version, found = excluded.found, map = excluded.map,
    analyzed_at = excluded.analyzed_at, used_at = excluded.used_at
`

type PutBeatMapParams struct {
	Provider   string
	TrackID    string
	Version    int64
	Found      bool
	Map        string
	AnalyzedAt time.Time
	UsedAt     time.Time
}

func (q *Queries) PutBeatMap(ctx context.Context, arg PutBeatMapParams) error {
	_, err := q.db.ExecContext(ctx, putBeatMap,
		arg.Provider,
		arg.TrackID,
		arg.Version,
		arg.Found,
		arg.Map,
		arg.AnalyzedAt,
		arg.UsedAt,
	)
	return err
}

const sweepBeatMaps = `-- name: SweepBeatMaps :execrows
DELETE FROM beat_maps
WHERE used_at < ?1 OR (NOT found AND analyzed_at < ?2)
`

type SweepBeatMapsParams struct {
	UnusedSince  time.Time
	MissedBefore time.Time
}

// SweepBeatMaps forgets maps nobody has played in a long while, and
// misses old enough to try again.
func (q *Queries) SweepBeatMaps(ctx context.Context, arg SweepBeatMapsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, sweepBeatMaps, arg.UnusedSince, arg.MissedBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchBeatMap = `-- name: TouchBeatMap :exec
UPDATE beat_maps SET used_at = ?1
WHERE provider = ?2 AND track_id = ?3 AND used_at < ?4
`

type TouchBeatMapParams struct {
	Now      time.Time
	Provider string
	TrackID  string
	Since    time.Time
}

// TouchBeatMap marks a map as used, at most once a day.
func (q *Queries) TouchBeatMap(ctx context.Context, arg TouchBeatMapParams) error {
	_, err := q.db.ExecContext(ctx, touchBeatMap,
		arg.Now,
		arg.Provider,
		arg.TrackID,
		arg.Since,
	)
	return err
}
