// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credentials.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const countPasskeys = `-- name: CountPasskeys :one
SELECT count(*) FROM credentials_passkey WHERE user_id = ?
`

func (q *Queries) CountPasskeys(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPasskeys, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPasskey = `-- name: CreatePasskey :one
INSERT INTO credentials_passkey (id, user_id, name, data, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, name, data, created_at, last_used_at
`

type CreatePasskeyParams struct {
	ID        []byte
	UserID    string
	Name      string
	Data      string
	CreatedAt time.Time
}

func (q *Queries) CreatePasskey(ctx context.Context, arg CreatePasskeyParams) (CredentialsPasskey, error) {
	row := q.db.QueryRowContext(ctx, createPasskey,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Data,
		arg.CreatedAt,
	)
	var i CredentialsPasskey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Data,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (token_hash, user_id, user_agent, created_at, last_seen_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING token_hash, user_id, user_agent, created_at, last_seen_at, expires_at
`

type CreateSessionParams struct {
	TokenHash  []byte
	UserID     string
	UserAgent  string
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.UserAgent,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOtherSessions = `-- name: DeleteOtherSessions :exec
DELETE FROM sessions WHERE user_id = ? AND token_hash <> ?
`

type DeleteOtherSessionsParams struct {
	UserID    string
	TokenHash []byte
}

func (q *Queries) DeleteOtherSessions(ctx context.Context, arg DeleteOtherSessionsParams) error {
	_, err := q.db.ExecContext(ctx, deleteOtherSessions, arg.UserID, arg.TokenHash)
	return err
}

const deletePasskey = `-- name: DeletePasskey :exec
DELETE FROM credentials_passkey WHERE id = ? AND user_id = ?
`

type DeletePasskeyParams struct {
	ID     []byte
	UserID string
}

func (q *Queries) DeletePasskey(ctx context.Context, arg DeletePasskeyParams) error {
	_, err := q.db.ExecContext(ctx, deletePasskey, arg.ID, arg.UserID)
	return err
}

const deletePassword = `-- name: DeletePassword :exec
DELETE FROM credentials_password WHERE user_id = ?
`

func (q *Queries) DeletePassword(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deletePassword, userID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = ?
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.ExecContext(ctx, deleteSession, tokenHash)
	return err
}

const deleteUserSession = `-- name: DeleteUserSession :execrows
DELETE FROM sessions WHERE token_hash = ? AND user_id = ?
`

type DeleteUserSessionParams struct {
	TokenHash []byte
	UserID    string
}

func (q *Queries) DeleteUserSession(ctx context.Context, arg DeleteUserSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUserSession, arg.TokenHash, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessions, userID)
	return err
}

const getPasskey = `-- name: GetPasskey :one
SELECT id, user_id, name, data, created_at, last_used_at FROM credentials_passkey WHERE id = ?
`

func (q *Queries) GetPasskey(ctx context.Context, id []byte) (CredentialsPasskey, error) {
	row := q.db.QueryRowContext(ctx, getPasskey, id)
	var i CredentialsPasskey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Data,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getPassword = `-- name: GetPassword :one
SELECT user_id, hash, updated_at FROM credentials_password WHERE user_id = ?
`

func (q *Queries) GetPassword(ctx context.Context, userID string) (CredentialsPassword, error) {
	row := q.db.QueryRowContext(ctx, getPassword, userID)
	var i CredentialsPassword
	err := row.Scan(&i.UserID, &i.Hash, &i.UpdatedAt)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT token_hash, user_id, user_agent, created_at, last_seen_at, expires_at FROM sessions WHERE token_hash = ?1 AND expires_at > ?2
`

type GetSessionParams struct {
	TokenHash []byte
	Now       time.Time
}

// GetSession returns an unexpired session.
func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, arg.TokenHash, arg.Now)
	var i Session
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listPasskeys = `-- name: ListPasskeys :many
SELECT id, user_id, name, data, created_at, last_used_at FROM credentials_passkey WHERE user_id = ? ORDER BY created_at
`

func (q *Queries) ListPasskeys(ctx context.Context, userID string) ([]CredentialsPasskey, error) {
	rows, err := q.db.QueryContext(ctx, listPasskeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CredentialsPasskey{}
	for rows.Next() {
		var i CredentialsPasskey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Data,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT token_hash, user_id, user_agent, created_at, last_seen_at, expires_at FROM sessions
WHERE user_id = ?1 AND expires_at > ?2
ORDER BY last_seen_at DESC, created_at DESC
`

type ListSessionsParams struct {
	UserID string
	Now    time.Time
}

// ListSessions returns a user's unexpired sessions, most recently used first.
func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions, arg.UserID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.TokenHash,
			&i.UserID,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renamePasskey = `-- name: RenamePasskey :exec
UPDATE credentials_passkey SET name = ? WHERE id = ? AND user_id = ?
`

type RenamePasskeyParams struct {
	Name   string
	ID     []byte
	UserID string
}

func (q *Queries) RenamePasskey(ctx context.Context, arg RenamePasskeyParams) error {
	_, err := q.db.ExecContext(ctx, renamePasskey, arg.Name, arg.ID, arg.UserID)
	return err
}

const setPassword = `-- name: SetPassword :exec
INSERT INTO credentials_password (user_id, hash, updated_at)
VALUES (?, ?, ?)
ON CONFLICT (user_id) DO UPDATE SET hash = excluded.hash, updated_at = excluded.updated_at
`

type SetPasswordParams struct {
	UserID    string
	Hash      string
	UpdatedAt time.Time
}

func (q *Queries) SetPassword(ctx context.Context, arg SetPasswordParams) error {
	_, err := q.db.ExecContext(ctx, setPassword, arg.UserID, arg.Hash, arg.UpdatedAt)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = ?, expires_at = ? WHERE token_hash = ?
`

type TouchSessionParams struct {
	LastSeenAt time.Time
	ExpiresAt  time.Time
	TokenHash  []byte
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.LastSeenAt, arg.ExpiresAt, arg.TokenHash)
	return err
}

const usePasskey = `-- name: UsePasskey :exec
UPDATE credentials_passkey SET data = ?, last_used_at = ? WHERE id = ?
`

type UsePasskeyParams struct {
	Data       string
	LastUsedAt sql.NullTime
	ID         []byte
}

// UsePasskey saves the credential record after a sign-in (new sign count, flags).
func (q *Queries) UsePasskey(ctx context.Context, arg UsePasskeyParams) error {
	_, err := q.db.ExecContext(ctx, usePasskey, arg.Data, arg.LastUsedAt, arg.ID)
	return err
}
