// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: displays.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const createDisplay = `-- name: CreateDisplay :one
INSERT INTO displays (id, token_hash, room_id, name, paired_by, audio, created_at, last_seen_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, token_hash, room_id, name, paired_by, created_at, last_seen_at, expires_at, audio
`

type CreateDisplayParams struct {
	ID         string
	TokenHash  []byte
	RoomID     string
	Name       string
	PairedBy   sql.NullString
	Audio      bool
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
}

func (q *Queries) CreateDisplay(ctx context.Context, arg CreateDisplayParams) (Display, error) {
	row := q.db.QueryRowContext(ctx, createDisplay,
		arg.ID,
		arg.TokenHash,
		arg.RoomID,
		arg.Name,
		arg.PairedBy,
		arg.Audio,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.ExpiresAt,
	)
	var i Display
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.RoomID,
		&i.Name,
		&i.PairedBy,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.Audio,
	)
	return i, err
}

const deleteDisplay = `-- name: DeleteDisplay :exec
DELETE FROM displays WHERE id = ?
`

func (q *Queries) DeleteDisplay(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDisplay, id)
	return err
}

const deleteDisplayByToken = `-- name: DeleteDisplayByToken :exec
DELETE FROM displays WHERE token_hash = ?
`

func (q *Queries) DeleteDisplayByToken(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.ExecContext(ctx, deleteDisplayByToken, tokenHash)
	return err
}

const deleteExpiredDisplays = `-- name: DeleteExpiredDisplays :exec
DELETE FROM displays WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredDisplays(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredDisplays, expiresAt)
	return err
}

const getDisplay = `-- name: GetDisplay :one
SELECT id, token_hash, room_id, name, paired_by, created_at, last_seen_at, expires_at, audio FROM displays WHERE id = ?
`

func (q *Queries) GetDisplay(ctx context.Context, id string) (Display, error) {
	row := q.db.QueryRowContext(ctx, getDisplay, id)
	var i Display
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.RoomID,
		&i.Name,
		&i.PairedBy,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.Audio,
	)
	return i, err
}

const getDisplayByToken = `-- name: GetDisplayByToken :one
SELECT id, token_hash, room_id, name, paired_by, created_at, last_seen_at, expires_at, audio FROM displays WHERE token_hash = ? AND expires_at > ?2
`

type GetDisplayByTokenParams struct {
	TokenHash []byte
	Now       time.Time
}

func (q *Queries) GetDisplayByToken(ctx context.Context, arg GetDisplayByTokenParams) (Display, error) {
	row := q.db.QueryRowContext(ctx, getDisplayByToken, arg.TokenHash, arg.Now)
	var i Display
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.RoomID,
		&i.Name,
		&i.PairedBy,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.Audio,
	)
	return i, err
}

const listDisplays = `-- name: ListDisplays :many
SELECT id, token_hash, room_id, name, paired_by, created_at, last_seen_at, expires_at, audio FROM displays WHERE room_id = ? AND expires_at > ?2 ORDER BY created_at
`

type ListDisplaysParams struct {
	RoomID string
	Now    time.Time
}

func (q *Queries) ListDisplays(ctx context.Context, arg ListDisplaysParams) ([]Display, error) {
	rows, err := q.db.QueryContext(ctx, listDisplays, arg.RoomID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Display{}
	for rows.Next() {
		var i Display
		if err := rows.Scan(
			&i.ID,
			&i.TokenHash,
			&i.RoomID,
			&i.Name,
			&i.PairedBy,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.Audio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDisplayAudio = `-- name: SetDisplayAudio :one
UPDATE displays SET audio = ? WHERE id = ? RETURNING id, token_hash, room_id, name, paired_by, created_at, last_seen_at, expires_at, audio
`

type SetDisplayAudioParams struct {
	Audio bool
	ID    string
}

func (q *Queries) SetDisplayAudio(ctx context.Context, arg SetDisplayAudioParams) (Display, error) {
	row := q.db.QueryRowContext(ctx, setDisplayAudio, arg.Audio, arg.ID)
	var i Display
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.RoomID,
		&i.Name,
		&i.PairedBy,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.Audio,
	)
	return i, err
}

const touchDisplay = `-- name: TouchDisplay :exec
UPDATE displays SET last_seen_at = ?, expires_at = ? WHERE id = ?
`

type TouchDisplayParams struct {
	LastSeenAt time.Time
	ExpiresAt  time.Time
	ID         string
}

func (q *Queries) TouchDisplay(ctx context.Context, arg TouchDisplayParams) error {
	_, err := q.db.ExecContext(ctx, touchDisplay, arg.LastSeenAt, arg.ExpiresAt, arg.ID)
	return err
}
