// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dj.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const addDJAffinity = `-- name: AddDJAffinity :exec
INSERT INTO dj_affinities (room_id, kind, key, member, name, likes, skips, last_night, last_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type AddDJAffinityParams struct {
	RoomID    string
	Kind      string
	Key       string
	Member    string
	Name      string
	Likes     float64
	Skips     float64
	LastNight int64
	LastAt    sql.NullTime
}

func (q *Queries) AddDJAffinity(ctx context.Context, arg AddDJAffinityParams) error {
	_, err := q.db.ExecContext(ctx, addDJAffinity,
		arg.RoomID,
		arg.Kind,
		arg.Key,
		arg.Member,
		arg.Name,
		arg.Likes,
		arg.Skips,
		arg.LastNight,
		arg.LastAt,
	)
	return err
}

const deleteDJAffinities = `-- name: DeleteDJAffinities :exec
DELETE FROM dj_affinities WHERE room_id = ?
`

func (q *Queries) DeleteDJAffinities(ctx context.Context, roomID string) error {
	_, err := q.db.ExecContext(ctx, deleteDJAffinities, roomID)
	return err
}

const getDJRoom = `-- name: GetDJRoom :one
SELECT room_id, nights, folded_through, updated_at FROM dj_rooms WHERE room_id = ?
`

func (q *Queries) GetDJRoom(ctx context.Context, roomID string) (DjRoom, error) {
	row := q.db.QueryRowContext(ctx, getDJRoom, roomID)
	var i DjRoom
	err := row.Scan(
		&i.RoomID,
		&i.Nights,
		&i.FoldedThrough,
		&i.UpdatedAt,
	)
	return i, err
}

const listDJAffinities = `-- name: ListDJAffinities :many
SELECT room_id, kind, "key", member, name, likes, skips, last_night, last_at FROM dj_affinities WHERE room_id = ? ORDER BY kind, key, member
`

func (q *Queries) ListDJAffinities(ctx context.Context, roomID string) ([]DjAffinity, error) {
	rows, err := q.db.QueryContext(ctx, listDJAffinities, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DjAffinity{}
	for rows.Next() {
		var i DjAffinity
		if err := rows.Scan(
			&i.RoomID,
			&i.Kind,
			&i.Key,
			&i.Member,
			&i.Name,
			&i.Likes,
			&i.Skips,
			&i.LastNight,
			&i.LastAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nightsAfter = `-- name: NightsAfter :many
SELECT id, room_id, started_at, ended_at, ended_by, plays, queue_item_id, hearts, awards FROM nights WHERE room_id = ?1 AND ended_at > ?2
ORDER BY ended_at DESC, id DESC LIMIT ?3
`

type NightsAfterParams struct {
	RoomID string
	After  time.Time
	Limit  int64
}

// NightsAfter returns a room's nights that ended after a time, newest
// first, at most limit.
func (q *Queries) NightsAfter(ctx context.Context, arg NightsAfterParams) ([]Night, error) {
	rows, err := q.db.QueryContext(ctx, nightsAfter, arg.RoomID, arg.After, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Night{}
	for rows.Next() {
		var i Night
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.StartedAt,
			&i.EndedAt,
			&i.EndedBy,
			&i.Plays,
			&i.QueueItemID,
			&i.Hearts,
			&i.Awards,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putDJRoom = `-- name: PutDJRoom :exec
INSERT INTO dj_rooms (room_id, nights, folded_through, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (room_id) DO UPDATE SET
    nights = excluded.nights, folded_through = excluded.folded_through, updated_at = excluded.updated_at
`

type PutDJRoomParams struct {
	RoomID        string
	Nights        int64
	FoldedThrough time.Time
	UpdatedAt     time.Time
}

func (q *Queries) PutDJRoom(ctx context.Context, arg PutDJRoomParams) error {
	_, err := q.db.ExecContext(ctx, putDJRoom,
		arg.RoomID,
		arg.Nights,
		arg.FoldedThrough,
		arg.UpdatedAt,
	)
	return err
}
