// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: games.sql

package store

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const countGameRoundsSince = `-- name: CountGameRoundsSince :one
SELECT count(DISTINCT coalesce(set_id, id)) FROM game_rounds
WHERE room_id = ?1 AND started_at >= ?2 AND kind IN (/*SLICE:kinds*/?)
`

type CountGameRoundsSinceParams struct {
	RoomID string
	Since  time.Time
	Kinds  []string
}

// CountGameRoundsSince counts a room's rounds of some kinds since a
// time, for the breaks-per-hour budget. A set of tunes counts once.
func (q *Queries) CountGameRoundsSince(ctx context.Context, arg CountGameRoundsSinceParams) (int64, error) {
	query := countGameRoundsSince
	var queryParams []interface{}
	queryParams = append(queryParams, arg.RoomID)
	queryParams = append(queryParams, arg.Since)
	if len(arg.Kinds) > 0 {
		for _, v := range arg.Kinds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:kinds*/?", strings.Repeat(",?", len(arg.Kinds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:kinds*/?", "NULL", 1)
	}
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGameAnswer = `-- name: CreateGameAnswer :exec
INSERT INTO game_answers (round_id, user_id, answer, correct, points, answered_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateGameAnswerParams struct {
	RoundID    string
	UserID     string
	Answer     string
	Correct    bool
	Points     int64
	AnsweredAt time.Time
}

func (q *Queries) CreateGameAnswer(ctx context.Context, arg CreateGameAnswerParams) error {
	_, err := q.db.ExecContext(ctx, createGameAnswer,
		arg.RoundID,
		arg.UserID,
		arg.Answer,
		arg.Correct,
		arg.Points,
		arg.AnsweredAt,
	)
	return err
}

const createGameRound = `-- name: CreateGameRound :exec
INSERT INTO game_rounds (id, room_id, queue_item_id, kind, question, started_by, started_at, revealed_at, set_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateGameRoundParams struct {
	ID          string
	RoomID      string
	QueueItemID sql.NullString
	Kind        string
	Question    string
	StartedBy   sql.NullString
	StartedAt   time.Time
	RevealedAt  time.Time
	SetID       sql.NullString
}

func (q *Queries) CreateGameRound(ctx context.Context, arg CreateGameRoundParams) error {
	_, err := q.db.ExecContext(ctx, createGameRound,
		arg.ID,
		arg.RoomID,
		arg.QueueItemID,
		arg.Kind,
		arg.Question,
		arg.StartedBy,
		arg.StartedAt,
		arg.RevealedAt,
		arg.SetID,
	)
	return err
}

const favoriteItems = `-- name: FavoriteItems :many
SELECT queue_items.id, queue_items.room_id, queue_items.added_by, queue_items.provider, queue_items.link_id, queue_items.track_id, queue_items.metadata, queue_items.state, queue_items.lane_position, queue_items.added_at, queue_items.updated_at, queue_items.via_provider, queue_items.via_link_id, queue_items.via_track_id, queue_items.palette, queue_items.autopilot, queue_items.removed_by, queue_items.resume_at,
       CAST((SELECT count(*) FROM hearts WHERE hearts.queue_item_id = queue_items.id) AS INTEGER) AS hearts
FROM queue_items
WHERE queue_items.room_id = ?1 AND EXISTS (
    SELECT 1 FROM play_history
    WHERE play_history.queue_item_id = queue_items.id AND play_history.end_reason = 'finished'
)
ORDER BY queue_items.added_at DESC
LIMIT ?2
`

type FavoriteItemsParams struct {
	RoomID string
	Limit  int64
}

type FavoriteItemsRow struct {
	QueueItem QueueItem
	Hearts    int64
}

// FavoriteItems lists a room's songs that played through, newest first,
// with their hearts: what name that tune draws the room's favorites from.
func (q *Queries) FavoriteItems(ctx context.Context, arg FavoriteItemsParams) ([]FavoriteItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, favoriteItems, arg.RoomID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FavoriteItemsRow{}
	for rows.Next() {
		var i FavoriteItemsRow
		if err := rows.Scan(
			&i.QueueItem.ID,
			&i.QueueItem.RoomID,
			&i.QueueItem.AddedBy,
			&i.QueueItem.Provider,
			&i.QueueItem.LinkID,
			&i.QueueItem.TrackID,
			&i.QueueItem.Metadata,
			&i.QueueItem.State,
			&i.QueueItem.LanePosition,
			&i.QueueItem.AddedAt,
			&i.QueueItem.UpdatedAt,
			&i.QueueItem.ViaProvider,
			&i.QueueItem.ViaLinkID,
			&i.QueueItem.ViaTrackID,
			&i.QueueItem.Palette,
			&i.QueueItem.Autopilot,
			&i.QueueItem.RemovedBy,
			&i.QueueItem.ResumeAt,
			&i.Hearts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const gameScoresSince = `-- name: GameScoresSince :many
SELECT game_answers.user_id,
       CAST(sum(game_answers.points) AS INTEGER) AS points,
       CAST(sum(game_answers.correct) AS INTEGER) AS correct,
       count(*) AS answered
FROM game_answers
JOIN game_rounds ON game_rounds.id = game_answers.round_id
WHERE game_rounds.room_id = ?1 AND game_rounds.started_at >= ?2
GROUP BY game_answers.user_id
ORDER BY points DESC, game_answers.user_id
`

type GameScoresSinceParams struct {
	RoomID string
	Since  time.Time
}

type GameScoresSinceRow struct {
	UserID   string
	Points   int64
	Correct  int64
	Answered int64
}

// GameScoresSince sums each player's points in a room's rounds since a
// time: the night's scores.
func (q *Queries) GameScoresSince(ctx context.Context, arg GameScoresSinceParams) ([]GameScoresSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, gameScoresSince, arg.RoomID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GameScoresSinceRow{}
	for rows.Next() {
		var i GameScoresSinceRow
		if err := rows.Scan(
			&i.UserID,
			&i.Points,
			&i.Correct,
			&i.Answered,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const higherLowerAnswersSince = `-- name: HigherLowerAnswersSince :many
SELECT game_answers.user_id, game_answers.correct
FROM game_answers
JOIN game_rounds ON game_rounds.id = game_answers.round_id
WHERE game_rounds.room_id = ?1 AND game_rounds.started_at >= ?2
  AND game_rounds.kind = 'year' AND json_extract(game_rounds.question, '$.Topic') = 'higher_lower'
ORDER BY game_rounds.started_at, game_rounds.id
`

type HigherLowerAnswersSinceParams struct {
	RoomID string
	Since  time.Time
}

type HigherLowerAnswersSinceRow struct {
	UserID  string
	Correct bool
}

// HigherLowerAnswersSince lists the answers to a room's higher-or-lower
// rounds since a time, oldest first, for the night's streaks.
func (q *Queries) HigherLowerAnswersSince(ctx context.Context, arg HigherLowerAnswersSinceParams) ([]HigherLowerAnswersSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, higherLowerAnswersSince, arg.RoomID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HigherLowerAnswersSinceRow{}
	for rows.Next() {
		var i HigherLowerAnswersSinceRow
		if err := rows.Scan(&i.UserID, &i.Correct); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
