// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: games.sql

package store

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const countGameRoundsSince = `-- name: CountGameRoundsSince :one
SELECT count(*) FROM game_rounds
WHERE room_id = ?1 AND started_at >= ?2 AND kind IN (/*SLICE:kinds*/?)
`

type CountGameRoundsSinceParams struct {
	RoomID string
	Since  time.Time
	Kinds  []string
}

// CountGameRoundsSince counts a room's rounds of some kinds since a
// time, for the breaks-per-hour budget.
func (q *Queries) CountGameRoundsSince(ctx context.Context, arg CountGameRoundsSinceParams) (int64, error) {
	query := countGameRoundsSince
	var queryParams []interface{}
	queryParams = append(queryParams, arg.RoomID)
	queryParams = append(queryParams, arg.Since)
	if len(arg.Kinds) > 0 {
		for _, v := range arg.Kinds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:kinds*/?", strings.Repeat(",?", len(arg.Kinds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:kinds*/?", "NULL", 1)
	}
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGameAnswer = `-- name: CreateGameAnswer :exec
INSERT INTO game_answers (round_id, user_id, answer, correct, points, answered_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateGameAnswerParams struct {
	RoundID    string
	UserID     string
	Answer     string
	Correct    bool
	Points     int64
	AnsweredAt time.Time
}

func (q *Queries) CreateGameAnswer(ctx context.Context, arg CreateGameAnswerParams) error {
	_, err := q.db.ExecContext(ctx, createGameAnswer,
		arg.RoundID,
		arg.UserID,
		arg.Answer,
		arg.Correct,
		arg.Points,
		arg.AnsweredAt,
	)
	return err
}

const createGameRound = `-- name: CreateGameRound :exec
INSERT INTO game_rounds (id, room_id, queue_item_id, kind, question, started_by, started_at, revealed_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateGameRoundParams struct {
	ID          string
	RoomID      string
	QueueItemID sql.NullString
	Kind        string
	Question    string
	StartedBy   sql.NullString
	StartedAt   time.Time
	RevealedAt  time.Time
}

func (q *Queries) CreateGameRound(ctx context.Context, arg CreateGameRoundParams) error {
	_, err := q.db.ExecContext(ctx, createGameRound,
		arg.ID,
		arg.RoomID,
		arg.QueueItemID,
		arg.Kind,
		arg.Question,
		arg.StartedBy,
		arg.StartedAt,
		arg.RevealedAt,
	)
	return err
}

const gameScoresSince = `-- name: GameScoresSince :many
SELECT game_answers.user_id,
       CAST(sum(game_answers.points) AS INTEGER) AS points,
       CAST(sum(game_answers.correct) AS INTEGER) AS correct,
       count(*) AS answered
FROM game_answers
JOIN game_rounds ON game_rounds.id = game_answers.round_id
WHERE game_rounds.room_id = ?1 AND game_rounds.started_at >= ?2
GROUP BY game_answers.user_id
ORDER BY points DESC, game_answers.user_id
`

type GameScoresSinceParams struct {
	RoomID string
	Since  time.Time
}

type GameScoresSinceRow struct {
	UserID   string
	Points   int64
	Correct  int64
	Answered int64
}

// GameScoresSince sums each player's points in a room's rounds since a
// time: the night's scores.
func (q *Queries) GameScoresSince(ctx context.Context, arg GameScoresSinceParams) ([]GameScoresSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, gameScoresSince, arg.RoomID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GameScoresSinceRow{}
	for rows.Next() {
		var i GameScoresSinceRow
		if err := rows.Scan(
			&i.UserID,
			&i.Points,
			&i.Correct,
			&i.Answered,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
