// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guests.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const countGuestSongs = `-- name: CountGuestSongs :one
SELECT count(*) FROM queue_items
WHERE room_id = ? AND added_by = ? AND autopilot IS NULL AND state != 'removed'
`

type CountGuestSongsParams struct {
	RoomID  string
	AddedBy string
}

// CountGuestSongs counts the songs a user added to a room themselves,
// toward a guest's limit. Songs they took back don't count.
func (q *Queries) CountGuestSongs(ctx context.Context, arg CountGuestSongsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGuestSongs, arg.RoomID, arg.AddedBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPassGuests = `-- name: CountPassGuests :one
SELECT count(*) FROM guests WHERE pass_id = ?
`

// CountPassGuests counts the guests who joined with a pass.
func (q *Queries) CountPassGuests(ctx context.Context, passID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPassGuests, passID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGuest = `-- name: CreateGuest :one
INSERT INTO guests (user_id, room_id, pass_id, created_at, expires_at)
VALUES (?, ?, ?, ?, ?)
RETURNING user_id, room_id, pass_id, created_at, expires_at, ended_at
`

type CreateGuestParams struct {
	UserID    string
	RoomID    string
	PassID    sql.NullString
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) CreateGuest(ctx context.Context, arg CreateGuestParams) (Guest, error) {
	row := q.db.QueryRowContext(ctx, createGuest,
		arg.UserID,
		arg.RoomID,
		arg.PassID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i Guest
	err := row.Scan(
		&i.UserID,
		&i.RoomID,
		&i.PassID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.EndedAt,
	)
	return i, err
}

const createGuestPass = `-- name: CreateGuestPass :one
INSERT INTO guest_passes (id, room_id, created_by, created_at, expires_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, room_id, created_by, created_at, expires_at, revoked_at
`

type CreateGuestPassParams struct {
	ID        string
	RoomID    string
	CreatedBy sql.NullString
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) CreateGuestPass(ctx context.Context, arg CreateGuestPassParams) (GuestPass, error) {
	row := q.db.QueryRowContext(ctx, createGuestPass,
		arg.ID,
		arg.RoomID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i GuestPass
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const createServerKey = `-- name: CreateServerKey :exec
INSERT INTO server_keys (name, key, created_at) VALUES (?, ?, ?) ON CONFLICT (name) DO NOTHING
`

type CreateServerKeyParams struct {
	Name      string
	Key       []byte
	CreatedAt time.Time
}

func (q *Queries) CreateServerKey(ctx context.Context, arg CreateServerKeyParams) error {
	_, err := q.db.ExecContext(ctx, createServerKey, arg.Name, arg.Key, arg.CreatedAt)
	return err
}

const currentGuestPass = `-- name: CurrentGuestPass :one
SELECT id, room_id, created_by, created_at, expires_at, revoked_at FROM guest_passes
WHERE room_id = ? AND revoked_at IS NULL AND expires_at > ?2
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type CurrentGuestPassParams struct {
	RoomID string
	Now    time.Time
}

// CurrentGuestPass is a room's newest pass that's still good.
func (q *Queries) CurrentGuestPass(ctx context.Context, arg CurrentGuestPassParams) (GuestPass, error) {
	row := q.db.QueryRowContext(ctx, currentGuestPass, arg.RoomID, arg.Now)
	var i GuestPass
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteOldGuestPasses = `-- name: DeleteOldGuestPasses :exec
DELETE FROM guest_passes WHERE guest_passes.expires_at <= ?1 AND NOT EXISTS (
    SELECT 1 FROM guests WHERE guests.pass_id = guest_passes.id AND guests.ended_at IS NULL
)
`

func (q *Queries) DeleteOldGuestPasses(ctx context.Context, before time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteOldGuestPasses, before)
	return err
}

const endGuest = `-- name: EndGuest :exec
UPDATE guests SET ended_at = ?1 WHERE user_id = ?2 AND ended_at IS NULL
`

type EndGuestParams struct {
	Now    sql.NullTime
	UserID string
}

func (q *Queries) EndGuest(ctx context.Context, arg EndGuestParams) error {
	_, err := q.db.ExecContext(ctx, endGuest, arg.Now, arg.UserID)
	return err
}

const getGuest = `-- name: GetGuest :one
SELECT user_id, room_id, pass_id, created_at, expires_at, ended_at FROM guests WHERE user_id = ?
`

func (q *Queries) GetGuest(ctx context.Context, userID string) (Guest, error) {
	row := q.db.QueryRowContext(ctx, getGuest, userID)
	var i Guest
	err := row.Scan(
		&i.UserID,
		&i.RoomID,
		&i.PassID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.EndedAt,
	)
	return i, err
}

const getGuestPass = `-- name: GetGuestPass :one
SELECT id, room_id, created_by, created_at, expires_at, revoked_at FROM guest_passes WHERE id = ?
`

func (q *Queries) GetGuestPass(ctx context.Context, id string) (GuestPass, error) {
	row := q.db.QueryRowContext(ctx, getGuestPass, id)
	var i GuestPass
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getServerKey = `-- name: GetServerKey :one
SELECT key FROM server_keys WHERE name = ?
`

func (q *Queries) GetServerKey(ctx context.Context, name string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getServerKey, name)
	var key []byte
	err := row.Scan(&key)
	return key, err
}

const listAllGuests = `-- name: ListAllGuests :many
SELECT user_id, room_id, pass_id, created_at, expires_at, ended_at FROM guests
`

func (q *Queries) ListAllGuests(ctx context.Context) ([]Guest, error) {
	rows, err := q.db.QueryContext(ctx, listAllGuests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Guest{}
	for rows.Next() {
		var i Guest
		if err := rows.Scan(
			&i.UserID,
			&i.RoomID,
			&i.PassID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredGuests = `-- name: ListExpiredGuests :many
SELECT user_id, room_id, pass_id, created_at, expires_at, ended_at FROM guests WHERE ended_at IS NULL AND expires_at <= ?1
`

// ListExpiredGuests returns guests whose time is up but who haven't been purged.
func (q *Queries) ListExpiredGuests(ctx context.Context, now time.Time) ([]Guest, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredGuests, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Guest{}
	for rows.Next() {
		var i Guest
		if err := rows.Scan(
			&i.UserID,
			&i.RoomID,
			&i.PassID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomGuestIDs = `-- name: ListRoomGuestIDs :many
SELECT user_id FROM guests WHERE room_id = ?
`

// ListRoomGuestIDs returns the user IDs of every guest a room ever had.
func (q *Queries) ListRoomGuestIDs(ctx context.Context, roomID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRoomGuestIDs, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomGuests = `-- name: ListRoomGuests :many
SELECT guests.user_id, guests.room_id, guests.pass_id, guests.created_at, guests.expires_at, guests.ended_at, users.id, users.username, users.display_name, users.avatar, users.color, users.role, users.created_at, users.disabled_at, users.removed_at
FROM guests JOIN users ON users.id = guests.user_id
WHERE guests.room_id = ? AND guests.ended_at IS NULL AND guests.expires_at > ?2
ORDER BY guests.created_at DESC
`

type ListRoomGuestsParams struct {
	RoomID string
	Now    time.Time
}

type ListRoomGuestsRow struct {
	Guest Guest
	User  User
}

// ListRoomGuests returns a room's guests who are still in, newest first.
func (q *Queries) ListRoomGuests(ctx context.Context, arg ListRoomGuestsParams) ([]ListRoomGuestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRoomGuests, arg.RoomID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoomGuestsRow{}
	for rows.Next() {
		var i ListRoomGuestsRow
		if err := rows.Scan(
			&i.Guest.UserID,
			&i.Guest.RoomID,
			&i.Guest.PassID,
			&i.Guest.CreatedAt,
			&i.Guest.ExpiresAt,
			&i.Guest.EndedAt,
			&i.User.ID,
			&i.User.Username,
			&i.User.DisplayName,
			&i.User.Avatar,
			&i.User.Color,
			&i.User.Role,
			&i.User.CreatedAt,
			&i.User.DisabledAt,
			&i.User.RemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeGuestPasses = `-- name: RevokeGuestPasses :exec
UPDATE guest_passes SET revoked_at = ?1 WHERE room_id = ?2 AND revoked_at IS NULL
`

type RevokeGuestPassesParams struct {
	Now    sql.NullTime
	RoomID string
}

func (q *Queries) RevokeGuestPasses(ctx context.Context, arg RevokeGuestPassesParams) error {
	_, err := q.db.ExecContext(ctx, revokeGuestPasses, arg.Now, arg.RoomID)
	return err
}
