// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (code, created_by, role, created_at, expires_at)
VALUES (?, ?, ?, ?, ?)
RETURNING code, created_by, role, created_at, expires_at, used_by, used_at
`

type CreateInviteParams struct {
	Code      string
	CreatedBy sql.NullString
	Role      string
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRowContext(ctx, createInvite,
		arg.Code,
		arg.CreatedBy,
		arg.Role,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.Code,
		&i.CreatedBy,
		&i.Role,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedBy,
		&i.UsedAt,
	)
	return i, err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM invites WHERE code = ?
`

func (q *Queries) DeleteInvite(ctx context.Context, code string) error {
	_, err := q.db.ExecContext(ctx, deleteInvite, code)
	return err
}

const getInvite = `-- name: GetInvite :one
SELECT code, created_by, role, created_at, expires_at, used_by, used_at FROM invites WHERE code = ?
`

func (q *Queries) GetInvite(ctx context.Context, code string) (Invite, error) {
	row := q.db.QueryRowContext(ctx, getInvite, code)
	var i Invite
	err := row.Scan(
		&i.Code,
		&i.CreatedBy,
		&i.Role,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedBy,
		&i.UsedAt,
	)
	return i, err
}

const listInvites = `-- name: ListInvites :many
SELECT code, created_by, role, created_at, expires_at, used_by, used_at FROM invites ORDER BY created_at DESC
`

func (q *Queries) ListInvites(ctx context.Context) ([]Invite, error) {
	rows, err := q.db.QueryContext(ctx, listInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invite{}
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.Code,
			&i.CreatedBy,
			&i.Role,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.UsedBy,
			&i.UsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInviteUsed = `-- name: MarkInviteUsed :one
UPDATE invites SET used_by = ?1, used_at = ?2
WHERE code = ?3 AND used_by IS NULL AND expires_at > ?4
RETURNING code, created_by, role, created_at, expires_at, used_by, used_at
`

type MarkInviteUsedParams struct {
	UserID sql.NullString
	UsedAt sql.NullTime
	Code   string
	Now    time.Time
}

// Use RedeemInvite, which wraps this with friendlier types.
func (q *Queries) MarkInviteUsed(ctx context.Context, arg MarkInviteUsedParams) (Invite, error) {
	row := q.db.QueryRowContext(ctx, markInviteUsed,
		arg.UserID,
		arg.UsedAt,
		arg.Code,
		arg.Now,
	)
	var i Invite
	err := row.Scan(
		&i.Code,
		&i.CreatedBy,
		&i.Role,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedBy,
		&i.UsedAt,
	)
	return i, err
}
