// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: liner_notes.sql

package store

import (
	"context"
	"time"
)

const deleteExpiredLinerNotes = `-- name: DeleteExpiredLinerNotes :exec
DELETE FROM liner_notes_cache WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredLinerNotes(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredLinerNotes, expiresAt)
	return err
}

const getCachedLinerNotes = `-- name: GetCachedLinerNotes :one
SELECT provider, track_id, found, notes, fetched_at, expires_at FROM liner_notes_cache WHERE provider = ? AND track_id = ? AND expires_at > ?3
`

type GetCachedLinerNotesParams struct {
	Provider string
	TrackID  string
	Now      time.Time
}

func (q *Queries) GetCachedLinerNotes(ctx context.Context, arg GetCachedLinerNotesParams) (LinerNotesCache, error) {
	row := q.db.QueryRowContext(ctx, getCachedLinerNotes, arg.Provider, arg.TrackID, arg.Now)
	var i LinerNotesCache
	err := row.Scan(
		&i.Provider,
		&i.TrackID,
		&i.Found,
		&i.Notes,
		&i.FetchedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const putCachedLinerNotes = `-- name: PutCachedLinerNotes :exec
INSERT INTO liner_notes_cache (provider, track_id, found, notes, fetched_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (provider, track_id) DO UPDATE SET
    found = excluded.found, notes = excluded.notes, fetched_at = excluded.fetched_at, expires_at = excluded.expires_at
`

type PutCachedLinerNotesParams struct {
	Provider  string
	TrackID   string
	Found     bool
	Notes     string
	FetchedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) PutCachedLinerNotes(ctx context.Context, arg PutCachedLinerNotesParams) error {
	_, err := q.db.ExecContext(ctx, putCachedLinerNotes,
		arg.Provider,
		arg.TrackID,
		arg.Found,
		arg.Notes,
		arg.FetchedAt,
		arg.ExpiresAt,
	)
	return err
}
