// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lyrics.sql

package store

import (
	"context"
	"time"
)

const deleteExpiredLyrics = `-- name: DeleteExpiredLyrics :exec
DELETE FROM lyrics_cache WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredLyrics(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredLyrics, expiresAt)
	return err
}

const getCachedLyrics = `-- name: GetCachedLyrics :one
SELECT provider, track_id, source, instrumental, plain, synced, fetched_at, expires_at FROM lyrics_cache WHERE provider = ? AND track_id = ? AND expires_at > ?3
`

type GetCachedLyricsParams struct {
	Provider string
	TrackID  string
	Now      time.Time
}

func (q *Queries) GetCachedLyrics(ctx context.Context, arg GetCachedLyricsParams) (LyricsCache, error) {
	row := q.db.QueryRowContext(ctx, getCachedLyrics, arg.Provider, arg.TrackID, arg.Now)
	var i LyricsCache
	err := row.Scan(
		&i.Provider,
		&i.TrackID,
		&i.Source,
		&i.Instrumental,
		&i.Plain,
		&i.Synced,
		&i.FetchedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const putCachedLyrics = `-- name: PutCachedLyrics :exec
INSERT INTO lyrics_cache (provider, track_id, source, instrumental, plain, synced, fetched_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (provider, track_id) DO UPDATE SET
    source = excluded.source, instrumental = excluded.instrumental, plain = excluded.plain,
    synced = excluded.synced, fetched_at = excluded.fetched_at, expires_at = excluded.expires_at
`

type PutCachedLyricsParams struct {
	Provider     string
	TrackID      string
	Source       string
	Instrumental bool
	Plain        string
	Synced       string
	FetchedAt    time.Time
	ExpiresAt    time.Time
}

func (q *Queries) PutCachedLyrics(ctx context.Context, arg PutCachedLyricsParams) error {
	_, err := q.db.ExecContext(ctx, putCachedLyrics,
		arg.Provider,
		arg.TrackID,
		arg.Source,
		arg.Instrumental,
		arg.Plain,
		arg.Synced,
		arg.FetchedAt,
		arg.ExpiresAt,
	)
	return err
}
