// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
	"time"
)

type CredentialsPasskey struct {
	ID         []byte
	UserID     string
	Name       string
	Data       string
	CreatedAt  time.Time
	LastUsedAt sql.NullTime
}

type CredentialsPassword struct {
	UserID    string
	Hash      string
	UpdatedAt time.Time
}

type Invite struct {
	Code      string
	CreatedBy sql.NullString
	Role      string
	CreatedAt time.Time
	ExpiresAt time.Time
	UsedBy    sql.NullString
	UsedAt    sql.NullTime
}

type PlayHistory struct {
	ID          string
	RoomID      string
	QueueItemID string
	StartedAt   time.Time
	EndedAt     sql.NullTime
	EndReason   sql.NullString
}

type QueueItem struct {
	ID           string
	RoomID       string
	AddedBy      string
	Provider     string
	LinkID       sql.NullString
	TrackID      string
	Metadata     string
	State        string
	LanePosition int64
	AddedAt      time.Time
	UpdatedAt    time.Time
}

type Room struct {
	ID             string
	Name           string
	OwnerID        string
	PlayerDeviceID sql.NullString
	FairnessMode   string
	Settings       string
	CreatedAt      time.Time
	QueueVersion   int64
}

type ServiceLink struct {
	ID                   string
	UserID               string
	Provider             string
	AccountID            string
	AccountLabel         string
	EncryptedCredentials []byte
	Status               string
	StatusDetail         string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	LastOkAt             sql.NullTime
	Shared               bool
}

type Session struct {
	TokenHash  []byte
	UserID     string
	UserAgent  string
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
}

type User struct {
	ID          string
	Username    string
	DisplayName string
	Avatar      sql.NullString
	Color       string
	Role        string
	CreatedAt   time.Time
}
