// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: musicgraph.sql

package store

import (
	"context"
	"time"
)

const deleteExpiredMusicGraphArtists = `-- name: DeleteExpiredMusicGraphArtists :exec
DELETE FROM musicgraph_artists WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredMusicGraphArtists(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredMusicGraphArtists, expiresAt)
	return err
}

const deleteExpiredMusicGraphTags = `-- name: DeleteExpiredMusicGraphTags :exec
DELETE FROM musicgraph_tags WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredMusicGraphTags(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredMusicGraphTags, expiresAt)
	return err
}

const deleteExpiredMusicGraphTracks = `-- name: DeleteExpiredMusicGraphTracks :exec
DELETE FROM musicgraph_tracks WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredMusicGraphTracks(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredMusicGraphTracks, expiresAt)
	return err
}

const getMusicGraphArtist = `-- name: GetMusicGraphArtist :one
SELECT "key", mbid, found, facts, fetched_at, expires_at FROM musicgraph_artists WHERE key = ? AND expires_at > ?2
`

type GetMusicGraphArtistParams struct {
	Key string
	Now time.Time
}

func (q *Queries) GetMusicGraphArtist(ctx context.Context, arg GetMusicGraphArtistParams) (MusicgraphArtist, error) {
	row := q.db.QueryRowContext(ctx, getMusicGraphArtist, arg.Key, arg.Now)
	var i MusicgraphArtist
	err := row.Scan(
		&i.Key,
		&i.Mbid,
		&i.Found,
		&i.Facts,
		&i.FetchedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getMusicGraphArtistByMBID = `-- name: GetMusicGraphArtistByMBID :one
SELECT "key", mbid, found, facts, fetched_at, expires_at FROM musicgraph_artists WHERE mbid = ? AND mbid != '' AND expires_at > ?2
ORDER BY fetched_at DESC LIMIT 1
`

type GetMusicGraphArtistByMBIDParams struct {
	Mbid string
	Now  time.Time
}

func (q *Queries) GetMusicGraphArtistByMBID(ctx context.Context, arg GetMusicGraphArtistByMBIDParams) (MusicgraphArtist, error) {
	row := q.db.QueryRowContext(ctx, getMusicGraphArtistByMBID, arg.Mbid, arg.Now)
	var i MusicgraphArtist
	err := row.Scan(
		&i.Key,
		&i.Mbid,
		&i.Found,
		&i.Facts,
		&i.FetchedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getMusicGraphTag = `-- name: GetMusicGraphTag :one
SELECT "key", found, facts, fetched_at, expires_at FROM musicgraph_tags WHERE key = ? AND expires_at > ?2
`

type GetMusicGraphTagParams struct {
	Key string
	Now time.Time
}

func (q *Queries) GetMusicGraphTag(ctx context.Context, arg GetMusicGraphTagParams) (MusicgraphTag, error) {
	row := q.db.QueryRowContext(ctx, getMusicGraphTag, arg.Key, arg.Now)
	var i MusicgraphTag
	err := row.Scan(
		&i.Key,
		&i.Found,
		&i.Facts,
		&i.FetchedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getMusicGraphTrack = `-- name: GetMusicGraphTrack :one
SELECT "key", found, facts, fetched_at, expires_at FROM musicgraph_tracks WHERE key = ? AND expires_at > ?2
`

type GetMusicGraphTrackParams struct {
	Key string
	Now time.Time
}

func (q *Queries) GetMusicGraphTrack(ctx context.Context, arg GetMusicGraphTrackParams) (MusicgraphTrack, error) {
	row := q.db.QueryRowContext(ctx, getMusicGraphTrack, arg.Key, arg.Now)
	var i MusicgraphTrack
	err := row.Scan(
		&i.Key,
		&i.Found,
		&i.Facts,
		&i.FetchedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listMusicGraphArtists = `-- name: ListMusicGraphArtists :many
SELECT "key", mbid, found, facts, fetched_at, expires_at FROM musicgraph_artists WHERE expires_at > ?1 ORDER BY fetched_at
`

func (q *Queries) ListMusicGraphArtists(ctx context.Context, now time.Time) ([]MusicgraphArtist, error) {
	rows, err := q.db.QueryContext(ctx, listMusicGraphArtists, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MusicgraphArtist{}
	for rows.Next() {
		var i MusicgraphArtist
		if err := rows.Scan(
			&i.Key,
			&i.Mbid,
			&i.Found,
			&i.Facts,
			&i.FetchedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMusicGraphTracks = `-- name: ListMusicGraphTracks :many
SELECT "key", found, facts, fetched_at, expires_at FROM musicgraph_tracks WHERE expires_at > ?1 ORDER BY fetched_at
`

func (q *Queries) ListMusicGraphTracks(ctx context.Context, now time.Time) ([]MusicgraphTrack, error) {
	rows, err := q.db.QueryContext(ctx, listMusicGraphTracks, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MusicgraphTrack{}
	for rows.Next() {
		var i MusicgraphTrack
		if err := rows.Scan(
			&i.Key,
			&i.Found,
			&i.Facts,
			&i.FetchedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putMusicGraphArtist = `-- name: PutMusicGraphArtist :exec
INSERT INTO musicgraph_artists (key, mbid, found, facts, fetched_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (key) DO UPDATE SET
    mbid = excluded.mbid, found = excluded.found, facts = excluded.facts,
    fetched_at = excluded.fetched_at, expires_at = excluded.expires_at
`

type PutMusicGraphArtistParams struct {
	Key       string
	Mbid      string
	Found     bool
	Facts     string
	FetchedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) PutMusicGraphArtist(ctx context.Context, arg PutMusicGraphArtistParams) error {
	_, err := q.db.ExecContext(ctx, putMusicGraphArtist,
		arg.Key,
		arg.Mbid,
		arg.Found,
		arg.Facts,
		arg.FetchedAt,
		arg.ExpiresAt,
	)
	return err
}

const putMusicGraphTag = `-- name: PutMusicGraphTag :exec
INSERT INTO musicgraph_tags (key, found, facts, fetched_at, expires_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (key) DO UPDATE SET
    found = excluded.found, facts = excluded.facts,
    fetched_at = excluded.fetched_at, expires_at = excluded.expires_at
`

type PutMusicGraphTagParams struct {
	Key       string
	Found     bool
	Facts     string
	FetchedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) PutMusicGraphTag(ctx context.Context, arg PutMusicGraphTagParams) error {
	_, err := q.db.ExecContext(ctx, putMusicGraphTag,
		arg.Key,
		arg.Found,
		arg.Facts,
		arg.FetchedAt,
		arg.ExpiresAt,
	)
	return err
}

const putMusicGraphTrack = `-- name: PutMusicGraphTrack :exec
INSERT INTO musicgraph_tracks (key, found, facts, fetched_at, expires_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (key) DO UPDATE SET
    found = excluded.found, facts = excluded.facts,
    fetched_at = excluded.fetched_at, expires_at = excluded.expires_at
`

type PutMusicGraphTrackParams struct {
	Key       string
	Found     bool
	Facts     string
	FetchedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) PutMusicGraphTrack(ctx context.Context, arg PutMusicGraphTrackParams) error {
	_, err := q.db.ExecContext(ctx, putMusicGraphTrack,
		arg.Key,
		arg.Found,
		arg.Facts,
		arg.FetchedAt,
		arg.ExpiresAt,
	)
	return err
}

const taggedArtists = `-- name: TaggedArtists :many
SELECT CAST(json_extract(musicgraph_artists.facts, '$.ref.name') AS TEXT) AS name,
  CAST(json_extract(tag.value, '$.weight') AS REAL) AS weight
FROM musicgraph_artists, json_each(musicgraph_artists.facts, '$.tags') AS tag
WHERE musicgraph_artists.found AND musicgraph_artists.expires_at > ?1
  AND lower(json_extract(tag.value, '$.name')) = lower(?2)
ORDER BY weight DESC
LIMIT ?3
`

type TaggedArtistsParams struct {
	Now   time.Time
	Tag   string
	Limit int64
}

type TaggedArtistsRow struct {
	Name   string
	Weight float64
}

// TaggedArtists are cached artists carrying a tag, most strongly first:
// a genre's artists when no source can say.
func (q *Queries) TaggedArtists(ctx context.Context, arg TaggedArtistsParams) ([]TaggedArtistsRow, error) {
	rows, err := q.db.QueryContext(ctx, taggedArtists, arg.Now, arg.Tag, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaggedArtistsRow{}
	for rows.Next() {
		var i TaggedArtistsRow
		if err := rows.Scan(&i.Name, &i.Weight); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
