// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: musicbrainz.sql

package store

import (
	"context"
	"time"
)

const deleteExpiredMusicBrainzTracks = `-- name: DeleteExpiredMusicBrainzTracks :exec
DELETE FROM musicbrainz_tracks WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredMusicBrainzTracks(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredMusicBrainzTracks, expiresAt)
	return err
}

const getMusicBrainzTrack = `-- name: GetMusicBrainzTrack :one
SELECT provider, track_id, recording_mbid, release_mbid, release_group_mbid, artist_mbid, method, resolved_at, expires_at FROM musicbrainz_tracks WHERE provider = ? AND track_id = ? AND expires_at > ?3
`

type GetMusicBrainzTrackParams struct {
	Provider string
	TrackID  string
	Now      time.Time
}

func (q *Queries) GetMusicBrainzTrack(ctx context.Context, arg GetMusicBrainzTrackParams) (MusicbrainzTrack, error) {
	row := q.db.QueryRowContext(ctx, getMusicBrainzTrack, arg.Provider, arg.TrackID, arg.Now)
	var i MusicbrainzTrack
	err := row.Scan(
		&i.Provider,
		&i.TrackID,
		&i.RecordingMbid,
		&i.ReleaseMbid,
		&i.ReleaseGroupMbid,
		&i.ArtistMbid,
		&i.Method,
		&i.ResolvedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const putMusicBrainzTrack = `-- name: PutMusicBrainzTrack :exec
INSERT INTO musicbrainz_tracks (provider, track_id, recording_mbid, release_mbid, release_group_mbid, artist_mbid, method, resolved_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (provider, track_id) DO UPDATE SET
    recording_mbid = excluded.recording_mbid, release_mbid = excluded.release_mbid,
    release_group_mbid = excluded.release_group_mbid, artist_mbid = excluded.artist_mbid,
    method = excluded.method, resolved_at = excluded.resolved_at, expires_at = excluded.expires_at
`

type PutMusicBrainzTrackParams struct {
	Provider         string
	TrackID          string
	RecordingMbid    string
	ReleaseMbid      string
	ReleaseGroupMbid string
	ArtistMbid       string
	Method           string
	ResolvedAt       time.Time
	ExpiresAt        time.Time
}

func (q *Queries) PutMusicBrainzTrack(ctx context.Context, arg PutMusicBrainzTrackParams) error {
	_, err := q.db.ExecContext(ctx, putMusicBrainzTrack,
		arg.Provider,
		arg.TrackID,
		arg.RecordingMbid,
		arg.ReleaseMbid,
		arg.ReleaseGroupMbid,
		arg.ArtistMbid,
		arg.Method,
		arg.ResolvedAt,
		arg.ExpiresAt,
	)
	return err
}
