// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: musicgraph.sql

package store

import (
	"context"
	"time"
)

const deleteExpiredMusicGraphArtists = `-- name: DeleteExpiredMusicGraphArtists :exec
DELETE FROM musicgraph_artists WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredMusicGraphArtists(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredMusicGraphArtists, expiresAt)
	return err
}

const deleteExpiredMusicGraphTracks = `-- name: DeleteExpiredMusicGraphTracks :exec
DELETE FROM musicgraph_tracks WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredMusicGraphTracks(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredMusicGraphTracks, expiresAt)
	return err
}

const getMusicGraphArtist = `-- name: GetMusicGraphArtist :one
SELECT "key", mbid, found, facts, fetched_at, expires_at FROM musicgraph_artists WHERE key = ? AND expires_at > ?2
`

type GetMusicGraphArtistParams struct {
	Key string
	Now time.Time
}

func (q *Queries) GetMusicGraphArtist(ctx context.Context, arg GetMusicGraphArtistParams) (MusicgraphArtist, error) {
	row := q.db.QueryRowContext(ctx, getMusicGraphArtist, arg.Key, arg.Now)
	var i MusicgraphArtist
	err := row.Scan(
		&i.Key,
		&i.Mbid,
		&i.Found,
		&i.Facts,
		&i.FetchedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getMusicGraphArtistByMBID = `-- name: GetMusicGraphArtistByMBID :one
SELECT "key", mbid, found, facts, fetched_at, expires_at FROM musicgraph_artists WHERE mbid = ? AND mbid != '' AND expires_at > ?2
ORDER BY fetched_at DESC LIMIT 1
`

type GetMusicGraphArtistByMBIDParams struct {
	Mbid string
	Now  time.Time
}

func (q *Queries) GetMusicGraphArtistByMBID(ctx context.Context, arg GetMusicGraphArtistByMBIDParams) (MusicgraphArtist, error) {
	row := q.db.QueryRowContext(ctx, getMusicGraphArtistByMBID, arg.Mbid, arg.Now)
	var i MusicgraphArtist
	err := row.Scan(
		&i.Key,
		&i.Mbid,
		&i.Found,
		&i.Facts,
		&i.FetchedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getMusicGraphTrack = `-- name: GetMusicGraphTrack :one
SELECT "key", found, facts, fetched_at, expires_at FROM musicgraph_tracks WHERE key = ? AND expires_at > ?2
`

type GetMusicGraphTrackParams struct {
	Key string
	Now time.Time
}

func (q *Queries) GetMusicGraphTrack(ctx context.Context, arg GetMusicGraphTrackParams) (MusicgraphTrack, error) {
	row := q.db.QueryRowContext(ctx, getMusicGraphTrack, arg.Key, arg.Now)
	var i MusicgraphTrack
	err := row.Scan(
		&i.Key,
		&i.Found,
		&i.Facts,
		&i.FetchedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const putMusicGraphArtist = `-- name: PutMusicGraphArtist :exec
INSERT INTO musicgraph_artists (key, mbid, found, facts, fetched_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (key) DO UPDATE SET
    mbid = excluded.mbid, found = excluded.found, facts = excluded.facts,
    fetched_at = excluded.fetched_at, expires_at = excluded.expires_at
`

type PutMusicGraphArtistParams struct {
	Key       string
	Mbid      string
	Found     bool
	Facts     string
	FetchedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) PutMusicGraphArtist(ctx context.Context, arg PutMusicGraphArtistParams) error {
	_, err := q.db.ExecContext(ctx, putMusicGraphArtist,
		arg.Key,
		arg.Mbid,
		arg.Found,
		arg.Facts,
		arg.FetchedAt,
		arg.ExpiresAt,
	)
	return err
}

const putMusicGraphTrack = `-- name: PutMusicGraphTrack :exec
INSERT INTO musicgraph_tracks (key, found, facts, fetched_at, expires_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (key) DO UPDATE SET
    found = excluded.found, facts = excluded.facts,
    fetched_at = excluded.fetched_at, expires_at = excluded.expires_at
`

type PutMusicGraphTrackParams struct {
	Key       string
	Found     bool
	Facts     string
	FetchedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) PutMusicGraphTrack(ctx context.Context, arg PutMusicGraphTrackParams) error {
	_, err := q.db.ExecContext(ctx, putMusicGraphTrack,
		arg.Key,
		arg.Found,
		arg.Facts,
		arg.FetchedAt,
		arg.ExpiresAt,
	)
	return err
}
