// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nights.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const addHeart = `-- name: AddHeart :exec
INSERT INTO hearts (queue_item_id, user_id, created_at) VALUES (?, ?, ?)
ON CONFLICT (queue_item_id, user_id) DO NOTHING
`

type AddHeartParams struct {
	QueueItemID string
	UserID      string
	CreatedAt   time.Time
}

func (q *Queries) AddHeart(ctx context.Context, arg AddHeartParams) error {
	_, err := q.db.ExecContext(ctx, addHeart, arg.QueueItemID, arg.UserID, arg.CreatedAt)
	return err
}

const createNight = `-- name: CreateNight :one
INSERT INTO nights (id, room_id, started_at, ended_at, ended_by, plays, queue_item_id, hearts)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, room_id, started_at, ended_at, ended_by, plays, queue_item_id, hearts, awards, bracket
`

type CreateNightParams struct {
	ID          string
	RoomID      string
	StartedAt   time.Time
	EndedAt     time.Time
	EndedBy     string
	Plays       int64
	QueueItemID sql.NullString
	Hearts      int64
}

func (q *Queries) CreateNight(ctx context.Context, arg CreateNightParams) (Night, error) {
	row := q.db.QueryRowContext(ctx, createNight,
		arg.ID,
		arg.RoomID,
		arg.StartedAt,
		arg.EndedAt,
		arg.EndedBy,
		arg.Plays,
		arg.QueueItemID,
		arg.Hearts,
	)
	var i Night
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndedBy,
		&i.Plays,
		&i.QueueItemID,
		&i.Hearts,
		&i.Awards,
		&i.Bracket,
	)
	return i, err
}

const firstPlayOf = `-- name: FirstPlayOf :one
SELECT id, room_id, queue_item_id, started_at, ended_at, end_reason FROM play_history WHERE queue_item_id = ? ORDER BY started_at LIMIT 1
`

// FirstPlayOf is when an item first started playing.
func (q *Queries) FirstPlayOf(ctx context.Context, queueItemID string) (PlayHistory, error) {
	row := q.db.QueryRowContext(ctx, firstPlayOf, queueItemID)
	var i PlayHistory
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.QueueItemID,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
	)
	return i, err
}

const heartCountsSince = `-- name: HeartCountsSince :many
SELECT hearts.queue_item_id, count(*) AS hearts
FROM hearts
JOIN play_history ON play_history.queue_item_id = hearts.queue_item_id
WHERE play_history.room_id = ?1 AND play_history.started_at >= ?2
GROUP BY hearts.queue_item_id
`

type HeartCountsSinceParams struct {
	RoomID string
	Since  time.Time
}

type HeartCountsSinceRow struct {
	QueueItemID string
	Hearts      int64
}

// HeartCountsSince counts hearts on a room's songs that started playing
// since a time.
func (q *Queries) HeartCountsSince(ctx context.Context, arg HeartCountsSinceParams) ([]HeartCountsSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, heartCountsSince, arg.RoomID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HeartCountsSinceRow{}
	for rows.Next() {
		var i HeartCountsSinceRow
		if err := rows.Scan(&i.QueueItemID, &i.Hearts); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lastNight = `-- name: LastNight :one
SELECT id, room_id, started_at, ended_at, ended_by, plays, queue_item_id, hearts, awards, bracket FROM nights WHERE room_id = ? ORDER BY ended_at DESC, id DESC LIMIT 1
`

func (q *Queries) LastNight(ctx context.Context, roomID string) (Night, error) {
	row := q.db.QueryRowContext(ctx, lastNight, roomID)
	var i Night
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndedBy,
		&i.Plays,
		&i.QueueItemID,
		&i.Hearts,
		&i.Awards,
		&i.Bracket,
	)
	return i, err
}

const listHearts = `-- name: ListHearts :many
SELECT user_id FROM hearts WHERE queue_item_id = ? ORDER BY created_at, user_id
`

func (q *Queries) ListHearts(ctx context.Context, queueItemID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listHearts, queueItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNights = `-- name: ListNights :many
SELECT id, room_id, started_at, ended_at, ended_by, plays, queue_item_id, hearts, awards, bracket FROM nights WHERE room_id = ? ORDER BY ended_at DESC, id DESC LIMIT ?
`

type ListNightsParams struct {
	RoomID string
	Limit  int64
}

func (q *Queries) ListNights(ctx context.Context, arg ListNightsParams) ([]Night, error) {
	rows, err := q.db.QueryContext(ctx, listNights, arg.RoomID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Night{}
	for rows.Next() {
		var i Night
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.StartedAt,
			&i.EndedAt,
			&i.EndedBy,
			&i.Plays,
			&i.QueueItemID,
			&i.Hearts,
			&i.Awards,
			&i.Bracket,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const playsSince = `-- name: PlaysSince :many
SELECT id, room_id, queue_item_id, started_at, ended_at, end_reason FROM (
    SELECT id, room_id, queue_item_id, started_at, ended_at, end_reason FROM play_history
    WHERE room_id = ?1 AND started_at > ?2
    ORDER BY started_at DESC, id DESC
    LIMIT ?3
) ORDER BY started_at, id
`

type PlaysSinceParams struct {
	RoomID string
	Since  time.Time
	Limit  int64
}

// PlaysSince returns a room's plays that started after a time, oldest
// first, at most limit of the latest. ended_at is NULL for the one playing.
func (q *Queries) PlaysSince(ctx context.Context, arg PlaysSinceParams) ([]PlayHistory, error) {
	rows, err := q.db.QueryContext(ctx, playsSince, arg.RoomID, arg.Since, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlayHistory{}
	for rows.Next() {
		var i PlayHistory
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.QueueItemID,
			&i.StartedAt,
			&i.EndedAt,
			&i.EndReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeHeart = `-- name: RemoveHeart :exec
DELETE FROM hearts WHERE queue_item_id = ? AND user_id = ?
`

type RemoveHeartParams struct {
	QueueItemID string
	UserID      string
}

func (q *Queries) RemoveHeart(ctx context.Context, arg RemoveHeartParams) error {
	_, err := q.db.ExecContext(ctx, removeHeart, arg.QueueItemID, arg.UserID)
	return err
}

const setNightAwards = `-- name: SetNightAwards :exec
UPDATE nights SET awards = ? WHERE id = ?
`

type SetNightAwardsParams struct {
	Awards string
	ID     string
}

func (q *Queries) SetNightAwards(ctx context.Context, arg SetNightAwardsParams) error {
	_, err := q.db.ExecContext(ctx, setNightAwards, arg.Awards, arg.ID)
	return err
}

const setNightBracket = `-- name: SetNightBracket :exec
UPDATE nights SET bracket = ? WHERE id = ?
`

type SetNightBracketParams struct {
	Bracket string
	ID      string
}

func (q *Queries) SetNightBracket(ctx context.Context, arg SetNightBracketParams) error {
	_, err := q.db.ExecContext(ctx, setNightBracket, arg.Bracket, arg.ID)
	return err
}
