// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playlists.sql

package store

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const addPlaylistSong = `-- name: AddPlaylistSong :exec
INSERT INTO playlist_songs (id, playlist_id, position, provider, link_id, track_id, metadata, added_by, added_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type AddPlaylistSongParams struct {
	ID         string
	PlaylistID string
	Position   int64
	Provider   string
	LinkID     sql.NullString
	TrackID    string
	Metadata   string
	AddedBy    sql.NullString
	AddedAt    time.Time
}

func (q *Queries) AddPlaylistSong(ctx context.Context, arg AddPlaylistSongParams) error {
	_, err := q.db.ExecContext(ctx, addPlaylistSong,
		arg.ID,
		arg.PlaylistID,
		arg.Position,
		arg.Provider,
		arg.LinkID,
		arg.TrackID,
		arg.Metadata,
		arg.AddedBy,
		arg.AddedAt,
	)
	return err
}

const countPlaylistSongs = `-- name: CountPlaylistSongs :one
SELECT count(*) FROM playlist_songs WHERE playlist_id = ?
`

func (q *Queries) CountPlaylistSongs(ctx context.Context, playlistID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlaylistSongs, playlistID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlaylist = `-- name: CreatePlaylist :one

INSERT INTO playlists (id, owner_id, name, room_id, night_room_id, night_from, night_to, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?8, ?8)
RETURNING id, owner_id, name, room_id, night_room_id, night_from, night_to, created_at, updated_at
`

type CreatePlaylistParams struct {
	ID          string
	OwnerID     string
	Name        string
	RoomID      sql.NullString
	NightRoomID sql.NullString
	NightFrom   sql.NullTime
	NightTo     sql.NullTime
	Now         time.Time
}

// Syncphony's own playlists (MAD-737).
func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (Playlist, error) {
	row := q.db.QueryRowContext(ctx, createPlaylist,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.RoomID,
		arg.NightRoomID,
		arg.NightFrom,
		arg.NightTo,
		arg.Now,
	)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.RoomID,
		&i.NightRoomID,
		&i.NightFrom,
		&i.NightTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlaylist = `-- name: DeletePlaylist :exec
DELETE FROM playlists WHERE id = ?
`

func (q *Queries) DeletePlaylist(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePlaylist, id)
	return err
}

const deletePlaylistSong = `-- name: DeletePlaylistSong :exec
DELETE FROM playlist_songs WHERE id = ?
`

func (q *Queries) DeletePlaylistSong(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePlaylistSong, id)
	return err
}

const getPlaylist = `-- name: GetPlaylist :one
SELECT id, owner_id, name, room_id, night_room_id, night_from, night_to, created_at, updated_at FROM playlists WHERE id = ?
`

func (q *Queries) GetPlaylist(ctx context.Context, id string) (Playlist, error) {
	row := q.db.QueryRowContext(ctx, getPlaylist, id)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.RoomID,
		&i.NightRoomID,
		&i.NightFrom,
		&i.NightTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlaylistSong = `-- name: GetPlaylistSong :one
SELECT id, playlist_id, position, provider, link_id, track_id, metadata, added_by, added_at FROM playlist_songs WHERE id = ?
`

func (q *Queries) GetPlaylistSong(ctx context.Context, id string) (PlaylistSong, error) {
	row := q.db.QueryRowContext(ctx, getPlaylistSong, id)
	var i PlaylistSong
	err := row.Scan(
		&i.ID,
		&i.PlaylistID,
		&i.Position,
		&i.Provider,
		&i.LinkID,
		&i.TrackID,
		&i.Metadata,
		&i.AddedBy,
		&i.AddedAt,
	)
	return i, err
}

const listPlaylistSongs = `-- name: ListPlaylistSongs :many
SELECT id, playlist_id, position, provider, link_id, track_id, metadata, added_by, added_at FROM playlist_songs WHERE playlist_id = ? ORDER BY position, id
`

func (q *Queries) ListPlaylistSongs(ctx context.Context, playlistID string) ([]PlaylistSong, error) {
	rows, err := q.db.QueryContext(ctx, listPlaylistSongs, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlaylistSong{}
	for rows.Next() {
		var i PlaylistSong
		if err := rows.Scan(
			&i.ID,
			&i.PlaylistID,
			&i.Position,
			&i.Provider,
			&i.LinkID,
			&i.TrackID,
			&i.Metadata,
			&i.AddedBy,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistsFor = `-- name: ListPlaylistsFor :many
SELECT playlists.id, playlists.owner_id, playlists.name, playlists.room_id, playlists.night_room_id, playlists.night_from, playlists.night_to, playlists.created_at, playlists.updated_at,
    CAST((SELECT count(*) FROM playlist_songs WHERE playlist_songs.playlist_id = playlists.id) AS INTEGER) AS songs
FROM playlists
WHERE owner_id = ?1 OR room_id IS NOT NULL
ORDER BY updated_at DESC, id DESC
`

type ListPlaylistsForRow struct {
	ID          string
	OwnerID     string
	Name        string
	RoomID      sql.NullString
	NightRoomID sql.NullString
	NightFrom   sql.NullTime
	NightTo     sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Songs       int64
}

// ListPlaylistsFor returns a user's own playlists and every playlist
// shared with a room, most recently changed first. Whether the user can
// enter those rooms is checked in Go.
func (q *Queries) ListPlaylistsFor(ctx context.Context, userID string) ([]ListPlaylistsForRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlaylistsFor, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlaylistsForRow{}
	for rows.Next() {
		var i ListPlaylistsForRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.RoomID,
			&i.NightRoomID,
			&i.NightFrom,
			&i.NightTo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Songs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nightPlaylists = `-- name: NightPlaylists :many
SELECT id, owner_id, name, room_id, night_room_id, night_from, night_to, created_at, updated_at FROM playlists
WHERE night_room_id = ?1 AND night_from >= ?2 AND night_from < ?3
ORDER BY created_at, id
`

type NightPlaylistsParams struct {
	RoomID sql.NullString
	FromAt sql.NullTime
	ToAt   sql.NullTime
}

// NightPlaylists returns the playlists saved from a room's night that
// began in [from, to).
func (q *Queries) NightPlaylists(ctx context.Context, arg NightPlaylistsParams) ([]Playlist, error) {
	rows, err := q.db.QueryContext(ctx, nightPlaylists, arg.RoomID, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Playlist{}
	for rows.Next() {
		var i Playlist
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.RoomID,
			&i.NightRoomID,
			&i.NightFrom,
			&i.NightTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const playlistCovers = `-- name: PlaylistCovers :many
SELECT id, playlist_id, position, provider, link_id, track_id, metadata, added_by, added_at FROM playlist_songs
WHERE playlist_id IN (/*SLICE:ids*/?) AND position < ?2
ORDER BY playlist_id, position
`

type PlaylistCoversParams struct {
	Ids []string
	N   int64
}

// PlaylistCovers returns the first few songs of each playlist given, for
// their covers.
func (q *Queries) PlaylistCovers(ctx context.Context, arg PlaylistCoversParams) ([]PlaylistSong, error) {
	query := playlistCovers
	var queryParams []interface{}
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.N)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlaylistSong{}
	for rows.Next() {
		var i PlaylistSong
		if err := rows.Scan(
			&i.ID,
			&i.PlaylistID,
			&i.Position,
			&i.Provider,
			&i.LinkID,
			&i.TrackID,
			&i.Metadata,
			&i.AddedBy,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPlaylistSongPosition = `-- name: SetPlaylistSongPosition :exec
UPDATE playlist_songs SET position = ? WHERE id = ?
`

type SetPlaylistSongPositionParams struct {
	Position int64
	ID       string
}

func (q *Queries) SetPlaylistSongPosition(ctx context.Context, arg SetPlaylistSongPositionParams) error {
	_, err := q.db.ExecContext(ctx, setPlaylistSongPosition, arg.Position, arg.ID)
	return err
}

const touchPlaylist = `-- name: TouchPlaylist :exec
UPDATE playlists SET updated_at = ? WHERE id = ?
`

type TouchPlaylistParams struct {
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) TouchPlaylist(ctx context.Context, arg TouchPlaylistParams) error {
	_, err := q.db.ExecContext(ctx, touchPlaylist, arg.UpdatedAt, arg.ID)
	return err
}

const updatePlaylist = `-- name: UpdatePlaylist :exec
UPDATE playlists SET name = ?, room_id = ?, updated_at = ? WHERE id = ?
`

type UpdatePlaylistParams struct {
	Name      string
	RoomID    sql.NullString
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) error {
	_, err := q.db.ExecContext(ctx, updatePlaylist,
		arg.Name,
		arg.RoomID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
