// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queue.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const addQueueItem = `-- name: AddQueueItem :one
INSERT INTO queue_items (id, room_id, added_by, provider, link_id, track_id, metadata, lane_position, autopilot, added_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?10, ?10)
RETURNING id, room_id, added_by, provider, link_id, track_id, metadata, state, lane_position, added_at, updated_at, via_provider, via_link_id, via_track_id, palette, autopilot, removed_by, resume_at, game_held, front_at
`

type AddQueueItemParams struct {
	ID           string
	RoomID       string
	AddedBy      string
	Provider     string
	LinkID       sql.NullString
	TrackID      string
	Metadata     string
	LanePosition int64
	Autopilot    sql.NullString
	Now          time.Time
}

func (q *Queries) AddQueueItem(ctx context.Context, arg AddQueueItemParams) (QueueItem, error) {
	row := q.db.QueryRowContext(ctx, addQueueItem,
		arg.ID,
		arg.RoomID,
		arg.AddedBy,
		arg.Provider,
		arg.LinkID,
		arg.TrackID,
		arg.Metadata,
		arg.LanePosition,
		arg.Autopilot,
		arg.Now,
	)
	var i QueueItem
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.AddedBy,
		&i.Provider,
		&i.LinkID,
		&i.TrackID,
		&i.Metadata,
		&i.State,
		&i.LanePosition,
		&i.AddedAt,
		&i.UpdatedAt,
		&i.ViaProvider,
		&i.ViaLinkID,
		&i.ViaTrackID,
		&i.Palette,
		&i.Autopilot,
		&i.RemovedBy,
		&i.ResumeAt,
		&i.GameHeld,
		&i.FrontAt,
	)
	return i, err
}

const deleteOpenPlays = `-- name: DeleteOpenPlays :exec
DELETE FROM play_history WHERE room_id = ? AND ended_at IS NULL
`

// EndOpenPlays closes a room's unfinished play_history rows. There is at
// most one: the playing item's.
// DeleteOpenPlays forgets a room's unfinished play, for a song put back
// in the queue: it'll play again from the start.
func (q *Queries) DeleteOpenPlays(ctx context.Context, roomID string) error {
	_, err := q.db.ExecContext(ctx, deleteOpenPlays, roomID)
	return err
}

const endOpenPlays = `-- name: EndOpenPlays :exec
UPDATE play_history SET ended_at = ?, end_reason = ? WHERE room_id = ? AND ended_at IS NULL
`

type EndOpenPlaysParams struct {
	EndedAt   sql.NullTime
	EndReason sql.NullString
	RoomID    string
}

func (q *Queries) EndOpenPlays(ctx context.Context, arg EndOpenPlaysParams) error {
	_, err := q.db.ExecContext(ctx, endOpenPlays, arg.EndedAt, arg.EndReason, arg.RoomID)
	return err
}

const endPlay = `-- name: EndPlay :exec
UPDATE play_history SET ended_at = ?, end_reason = ? WHERE id = ? AND ended_at IS NULL
`

type EndPlayParams struct {
	EndedAt   sql.NullTime
	EndReason sql.NullString
	ID        string
}

func (q *Queries) EndPlay(ctx context.Context, arg EndPlayParams) error {
	_, err := q.db.ExecContext(ctx, endPlay, arg.EndedAt, arg.EndReason, arg.ID)
	return err
}

const frontQueueItem = `-- name: FrontQueueItem :exec
UPDATE queue_items SET game_held = FALSE, front_at = ?, updated_at = ? WHERE id = ? AND state = 'queued'
`

type FrontQueueItemParams struct {
	FrontAt   sql.NullTime
	UpdatedAt time.Time
	ID        string
}

// FrontQueueItem plays a waiting song a game held, or any, before the fair
// order: the earliest front_at first.
func (q *Queries) FrontQueueItem(ctx context.Context, arg FrontQueueItemParams) error {
	_, err := q.db.ExecContext(ctx, frontQueueItem, arg.FrontAt, arg.UpdatedAt, arg.ID)
	return err
}

const getPlaying = `-- name: GetPlaying :one
SELECT id, room_id, added_by, provider, link_id, track_id, metadata, state, lane_position, added_at, updated_at, via_provider, via_link_id, via_track_id, palette, autopilot, removed_by, resume_at, game_held, front_at FROM queue_items WHERE room_id = ? AND state = 'playing'
`

func (q *Queries) GetPlaying(ctx context.Context, roomID string) (QueueItem, error) {
	row := q.db.QueryRowContext(ctx, getPlaying, roomID)
	var i QueueItem
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.AddedBy,
		&i.Provider,
		&i.LinkID,
		&i.TrackID,
		&i.Metadata,
		&i.State,
		&i.LanePosition,
		&i.AddedAt,
		&i.UpdatedAt,
		&i.ViaProvider,
		&i.ViaLinkID,
		&i.ViaTrackID,
		&i.Palette,
		&i.Autopilot,
		&i.RemovedBy,
		&i.ResumeAt,
		&i.GameHeld,
		&i.FrontAt,
	)
	return i, err
}

const getQueueItem = `-- name: GetQueueItem :one
SELECT id, room_id, added_by, provider, link_id, track_id, metadata, state, lane_position, added_at, updated_at, via_provider, via_link_id, via_track_id, palette, autopilot, removed_by, resume_at, game_held, front_at FROM queue_items WHERE id = ?
`

func (q *Queries) GetQueueItem(ctx context.Context, id string) (QueueItem, error) {
	row := q.db.QueryRowContext(ctx, getQueueItem, id)
	var i QueueItem
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.AddedBy,
		&i.Provider,
		&i.LinkID,
		&i.TrackID,
		&i.Metadata,
		&i.State,
		&i.LanePosition,
		&i.AddedAt,
		&i.UpdatedAt,
		&i.ViaProvider,
		&i.ViaLinkID,
		&i.ViaTrackID,
		&i.Palette,
		&i.Autopilot,
		&i.RemovedBy,
		&i.ResumeAt,
		&i.GameHeld,
		&i.FrontAt,
	)
	return i, err
}

const holdQueueItem = `-- name: HoldQueueItem :exec
UPDATE queue_items SET game_held = ?, front_at = NULL, updated_at = ? WHERE id = ? AND state = 'queued'
`

type HoldQueueItemParams struct {
	GameHeld  bool
	UpdatedAt time.Time
	ID        string
}

// HoldQueueItem holds a waiting song out of the play order for a game, or
// lets it back in.
func (q *Queries) HoldQueueItem(ctx context.Context, arg HoldQueueItemParams) error {
	_, err := q.db.ExecContext(ctx, holdQueueItem, arg.GameHeld, arg.UpdatedAt, arg.ID)
	return err
}

const lastPlayedByUser = `-- name: LastPlayedByUser :many
SELECT queue_items.added_by AS user_id, play_history.started_at
FROM play_history
JOIN queue_items ON queue_items.id = play_history.queue_item_id
WHERE play_history.room_id = ?1
  AND queue_items.autopilot IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM play_history AS later
    JOIN queue_items AS later_item ON later_item.id = later.queue_item_id
    WHERE later.room_id = play_history.room_id
      AND later_item.added_by = queue_items.added_by
      AND later_item.autopilot IS NULL
      AND later.started_at > play_history.started_at
  )
`

type LastPlayedByUserRow struct {
	UserID    string
	StartedAt time.Time
}

// LastPlayedByUser is when each user's most recent song started in a room,
// for the fairness engine. It selects the column itself, not max(), so the
// driver still knows it's a timestamp. Autopilot songs aren't anyone's turn.
func (q *Queries) LastPlayedByUser(ctx context.Context, roomID string) ([]LastPlayedByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, lastPlayedByUser, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LastPlayedByUserRow{}
	for rows.Next() {
		var i LastPlayedByUserRow
		if err := rows.Scan(&i.UserID, &i.StartedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutopilot = `-- name: ListAutopilot :many
SELECT id, room_id, added_by, provider, link_id, track_id, metadata, state, lane_position, added_at, updated_at, via_provider, via_link_id, via_track_id, palette, autopilot, removed_by, resume_at, game_held, front_at FROM queue_items
WHERE room_id = ? AND autopilot IS NOT NULL
ORDER BY added_at DESC, id DESC
LIMIT ?
`

type ListAutopilotParams struct {
	RoomID string
	Limit  int64
}

// ListAutopilot returns a room's most recent autopilot items in any state,
// newest first: who autopilot last chose songs for, and which songs the
// room skipped or removed.
func (q *Queries) ListAutopilot(ctx context.Context, arg ListAutopilotParams) ([]QueueItem, error) {
	rows, err := q.db.QueryContext(ctx, listAutopilot, arg.RoomID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QueueItem{}
	for rows.Next() {
		var i QueueItem
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.AddedBy,
			&i.Provider,
			&i.LinkID,
			&i.TrackID,
			&i.Metadata,
			&i.State,
			&i.LanePosition,
			&i.AddedAt,
			&i.UpdatedAt,
			&i.ViaProvider,
			&i.ViaLinkID,
			&i.ViaTrackID,
			&i.Palette,
			&i.Autopilot,
			&i.RemovedBy,
			&i.ResumeAt,
			&i.GameHeld,
			&i.FrontAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHistory = `-- name: ListHistory :many
SELECT play_history.id, play_history.room_id, play_history.queue_item_id, play_history.started_at, play_history.ended_at, play_history.end_reason, queue_items.id, queue_items.room_id, queue_items.added_by, queue_items.provider, queue_items.link_id, queue_items.track_id, queue_items.metadata, queue_items.state, queue_items.lane_position, queue_items.added_at, queue_items.updated_at, queue_items.via_provider, queue_items.via_link_id, queue_items.via_track_id, queue_items.palette, queue_items.autopilot, queue_items.removed_by, queue_items.resume_at, queue_items.game_held, queue_items.front_at
FROM play_history
JOIN queue_items ON queue_items.id = play_history.queue_item_id
WHERE play_history.room_id = ?
ORDER BY play_history.started_at DESC
LIMIT ?
`

type ListHistoryParams struct {
	RoomID string
	Limit  int64
}

type ListHistoryRow struct {
	PlayHistory PlayHistory
	QueueItem   QueueItem
}

func (q *Queries) ListHistory(ctx context.Context, arg ListHistoryParams) ([]ListHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listHistory, arg.RoomID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHistoryRow{}
	for rows.Next() {
		var i ListHistoryRow
		if err := rows.Scan(
			&i.PlayHistory.ID,
			&i.PlayHistory.RoomID,
			&i.PlayHistory.QueueItemID,
			&i.PlayHistory.StartedAt,
			&i.PlayHistory.EndedAt,
			&i.PlayHistory.EndReason,
			&i.QueueItem.ID,
			&i.QueueItem.RoomID,
			&i.QueueItem.AddedBy,
			&i.QueueItem.Provider,
			&i.QueueItem.LinkID,
			&i.QueueItem.TrackID,
			&i.QueueItem.Metadata,
			&i.QueueItem.State,
			&i.QueueItem.LanePosition,
			&i.QueueItem.AddedAt,
			&i.QueueItem.UpdatedAt,
			&i.QueueItem.ViaProvider,
			&i.QueueItem.ViaLinkID,
			&i.QueueItem.ViaTrackID,
			&i.QueueItem.Palette,
			&i.QueueItem.Autopilot,
			&i.QueueItem.RemovedBy,
			&i.QueueItem.ResumeAt,
			&i.QueueItem.GameHeld,
			&i.QueueItem.FrontAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLane = `-- name: ListLane :many
SELECT id, room_id, added_by, provider, link_id, track_id, metadata, state, lane_position, added_at, updated_at, via_provider, via_link_id, via_track_id, palette, autopilot, removed_by, resume_at, game_held, front_at FROM queue_items
WHERE room_id = ? AND added_by = ? AND state = 'queued' AND autopilot IS NULL
ORDER BY lane_position, added_at
`

type ListLaneParams struct {
	RoomID  string
	AddedBy string
}

// ListLane returns one user's queued items in a room, in lane order.
func (q *Queries) ListLane(ctx context.Context, arg ListLaneParams) ([]QueueItem, error) {
	rows, err := q.db.QueryContext(ctx, listLane, arg.RoomID, arg.AddedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QueueItem{}
	for rows.Next() {
		var i QueueItem
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.AddedBy,
			&i.Provider,
			&i.LinkID,
			&i.TrackID,
			&i.Metadata,
			&i.State,
			&i.LanePosition,
			&i.AddedAt,
			&i.UpdatedAt,
			&i.ViaProvider,
			&i.ViaLinkID,
			&i.ViaTrackID,
			&i.Palette,
			&i.Autopilot,
			&i.RemovedBy,
			&i.ResumeAt,
			&i.GameHeld,
			&i.FrontAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayTimes = `-- name: ListPlayTimes :many
SELECT play_history.started_at, play_history.ended_at,
  CAST(CASE WHEN queue_items.autopilot IS NULL THEN queue_items.added_by ELSE '' END AS TEXT) AS added_by
FROM play_history
JOIN queue_items ON queue_items.id = play_history.queue_item_id
WHERE play_history.room_id = ? AND play_history.ended_at IS NOT NULL
ORDER BY play_history.started_at, play_history.id
LIMIT ?
`

type ListPlayTimesParams struct {
	RoomID string
	Limit  int64
}

type ListPlayTimesRow struct {
	StartedAt time.Time
	EndedAt   sql.NullTime
	AddedBy   string
}

// ListPlayTimes returns when each of a room's finished plays started and
// ended, and whose song it was (” for autopilot), oldest first, to find
// sessions.
func (q *Queries) ListPlayTimes(ctx context.Context, arg ListPlayTimesParams) ([]ListPlayTimesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlayTimes, arg.RoomID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayTimesRow{}
	for rows.Next() {
		var i ListPlayTimesRow
		if err := rows.Scan(&i.StartedAt, &i.EndedAt, &i.AddedBy); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayed = `-- name: ListPlayed :many
SELECT play_history.id, play_history.room_id, play_history.queue_item_id, play_history.started_at, play_history.ended_at, play_history.end_reason, queue_items.id, queue_items.room_id, queue_items.added_by, queue_items.provider, queue_items.link_id, queue_items.track_id, queue_items.metadata, queue_items.state, queue_items.lane_position, queue_items.added_at, queue_items.updated_at, queue_items.via_provider, queue_items.via_link_id, queue_items.via_track_id, queue_items.palette, queue_items.autopilot, queue_items.removed_by, queue_items.resume_at, queue_items.game_held, queue_items.front_at
FROM play_history
JOIN queue_items ON queue_items.id = play_history.queue_item_id
WHERE play_history.room_id = ?1
  AND play_history.ended_at IS NOT NULL
  AND play_history.started_at < ?2
  AND (CAST(?3 AS TEXT) = '' OR (queue_items.added_by = ?3 AND queue_items.autopilot IS NULL))
ORDER BY play_history.started_at DESC, play_history.id DESC
LIMIT ?4
`

type ListPlayedParams struct {
	RoomID string
	Before time.Time
	UserID string
	Limit  int64
}

type ListPlayedRow struct {
	PlayHistory PlayHistory
	QueueItem   QueueItem
}

// ListPlayed returns a room's finished plays (not the one in progress)
// that started before a time, newest first, optionally only one user's
// songs (autopilot songs are nobody's). Pages go back by passing the last
// row's started_at.
func (q *Queries) ListPlayed(ctx context.Context, arg ListPlayedParams) ([]ListPlayedRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlayed,
		arg.RoomID,
		arg.Before,
		arg.UserID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayedRow{}
	for rows.Next() {
		var i ListPlayedRow
		if err := rows.Scan(
			&i.PlayHistory.ID,
			&i.PlayHistory.RoomID,
			&i.PlayHistory.QueueItemID,
			&i.PlayHistory.StartedAt,
			&i.PlayHistory.EndedAt,
			&i.PlayHistory.EndReason,
			&i.QueueItem.ID,
			&i.QueueItem.RoomID,
			&i.QueueItem.AddedBy,
			&i.QueueItem.Provider,
			&i.QueueItem.LinkID,
			&i.QueueItem.TrackID,
			&i.QueueItem.Metadata,
			&i.QueueItem.State,
			&i.QueueItem.LanePosition,
			&i.QueueItem.AddedAt,
			&i.QueueItem.UpdatedAt,
			&i.QueueItem.ViaProvider,
			&i.QueueItem.ViaLinkID,
			&i.QueueItem.ViaTrackID,
			&i.QueueItem.Palette,
			&i.QueueItem.Autopilot,
			&i.QueueItem.RemovedBy,
			&i.QueueItem.ResumeAt,
			&i.QueueItem.GameHeld,
			&i.QueueItem.FrontAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaysBetween = `-- name: ListPlaysBetween :many
SELECT play_history.id, play_history.room_id, play_history.queue_item_id, play_history.started_at, play_history.ended_at, play_history.end_reason, queue_items.id, queue_items.room_id, queue_items.added_by, queue_items.provider, queue_items.link_id, queue_items.track_id, queue_items.metadata, queue_items.state, queue_items.lane_position, queue_items.added_at, queue_items.updated_at, queue_items.via_provider, queue_items.via_link_id, queue_items.via_track_id, queue_items.palette, queue_items.autopilot, queue_items.removed_by, queue_items.resume_at, queue_items.game_held, queue_items.front_at
FROM play_history
JOIN queue_items ON queue_items.id = play_history.queue_item_id
WHERE play_history.room_id = ?1
  AND play_history.ended_at IS NOT NULL
  AND play_history.started_at >= ?2 AND play_history.started_at < ?3
ORDER BY play_history.started_at, play_history.id
LIMIT ?4
`

type ListPlaysBetweenParams struct {
	RoomID   string
	FromTime time.Time
	ToTime   time.Time
	Limit    int64
}

type ListPlaysBetweenRow struct {
	PlayHistory PlayHistory
	QueueItem   QueueItem
}

// ListPlaysBetween returns a room's finished plays that started in
// [from, to), oldest first, for stats.
func (q *Queries) ListPlaysBetween(ctx context.Context, arg ListPlaysBetweenParams) ([]ListPlaysBetweenRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlaysBetween,
		arg.RoomID,
		arg.FromTime,
		arg.ToTime,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlaysBetweenRow{}
	for rows.Next() {
		var i ListPlaysBetweenRow
		if err := rows.Scan(
			&i.PlayHistory.ID,
			&i.PlayHistory.RoomID,
			&i.PlayHistory.QueueItemID,
			&i.PlayHistory.StartedAt,
			&i.PlayHistory.EndedAt,
			&i.PlayHistory.EndReason,
			&i.QueueItem.ID,
			&i.QueueItem.RoomID,
			&i.QueueItem.AddedBy,
			&i.QueueItem.Provider,
			&i.QueueItem.LinkID,
			&i.QueueItem.TrackID,
			&i.QueueItem.Metadata,
			&i.QueueItem.State,
			&i.QueueItem.LanePosition,
			&i.QueueItem.AddedAt,
			&i.QueueItem.UpdatedAt,
			&i.QueueItem.ViaProvider,
			&i.QueueItem.ViaLinkID,
			&i.QueueItem.ViaTrackID,
			&i.QueueItem.Palette,
			&i.QueueItem.Autopilot,
			&i.QueueItem.RemovedBy,
			&i.QueueItem.ResumeAt,
			&i.QueueItem.GameHeld,
			&i.QueueItem.FrontAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcoming = `-- name: ListUpcoming :many
SELECT id, room_id, added_by, provider, link_id, track_id, metadata, state, lane_position, added_at, updated_at, via_provider, via_link_id, via_track_id, palette, autopilot, removed_by, resume_at, game_held, front_at FROM queue_items
WHERE room_id = ? AND state IN ('queued', 'playing')
ORDER BY added_by, lane_position, added_at
`

// ListUpcoming returns the playing item and queued items, each lane in
// order. The fairness engine interleaves the lanes.
func (q *Queries) ListUpcoming(ctx context.Context, roomID string) ([]QueueItem, error) {
	rows, err := q.db.QueryContext(ctx, listUpcoming, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QueueItem{}
	for rows.Next() {
		var i QueueItem
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.AddedBy,
			&i.Provider,
			&i.LinkID,
			&i.TrackID,
			&i.Metadata,
			&i.State,
			&i.LanePosition,
			&i.AddedAt,
			&i.UpdatedAt,
			&i.ViaProvider,
			&i.ViaLinkID,
			&i.ViaTrackID,
			&i.Palette,
			&i.Autopilot,
			&i.RemovedBy,
			&i.ResumeAt,
			&i.GameHeld,
			&i.FrontAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveQueueItem = `-- name: MoveQueueItem :exec
UPDATE queue_items SET lane_position = ?, resume_at = NULL, updated_at = ? WHERE id = ? AND state = 'queued'
`

type MoveQueueItemParams struct {
	LanePosition int64
	UpdatedAt    time.Time
	ID           string
}

// MoveQueueItem also gives up a place at the front: it goes where it's put.
func (q *Queries) MoveQueueItem(ctx context.Context, arg MoveQueueItemParams) error {
	_, err := q.db.ExecContext(ctx, moveQueueItem, arg.LanePosition, arg.UpdatedAt, arg.ID)
	return err
}

const nextLanePosition = `-- name: NextLanePosition :one
SELECT CAST(coalesce(max(lane_position), 0) + 1024 AS INTEGER)
FROM queue_items
WHERE room_id = ? AND added_by = ? AND state = 'queued' AND autopilot IS NULL
`

type NextLanePositionParams struct {
	RoomID  string
	AddedBy string
}

// NextLanePosition is where a new item goes at the end of a user's lane.
// Autopilot items aren't in anyone's lane.
func (q *Queries) NextLanePosition(ctx context.Context, arg NextLanePositionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextLanePosition, arg.RoomID, arg.AddedBy)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const recentDuplicates = `-- name: RecentDuplicates :one
SELECT count(*) FROM queue_items
WHERE queue_items.room_id = ?1
  AND (
    (queue_items.provider = ?2 AND queue_items.track_id = ?3)
    OR (CAST(?4 AS TEXT) != '' AND json_extract(queue_items.metadata, '$.ISRC') = ?4)
  )
  AND (
    queue_items.state IN ('queued', 'playing')
    OR EXISTS (
      SELECT 1 FROM play_history
      WHERE play_history.queue_item_id = queue_items.id AND play_history.started_at >= ?5
    )
  )
`

type RecentDuplicatesParams struct {
	RoomID   string
	Provider string
	TrackID  string
	Isrc     string
	Since    time.Time
}

// RecentDuplicates counts a room's items for the same song (the same
// track, or the same ISRC on any service) that are waiting, playing, or
// started playing since a time, for the repeat guard. metadata is a
// provider.Track, whose ISRC field has no JSON tag.
func (q *Queries) RecentDuplicates(ctx context.Context, arg RecentDuplicatesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, recentDuplicates,
		arg.RoomID,
		arg.Provider,
		arg.TrackID,
		arg.Isrc,
		arg.Since,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const recentPlayers = `-- name: RecentPlayers :many
SELECT CAST(CASE WHEN queue_items.autopilot IS NULL THEN queue_items.added_by ELSE '' END AS TEXT) AS added_by
FROM play_history
JOIN queue_items ON queue_items.id = play_history.queue_item_id
WHERE play_history.room_id = ?
ORDER BY play_history.started_at DESC, play_history.id DESC
LIMIT ?
`

type RecentPlayersParams struct {
	RoomID string
	Limit  int64
}

// RecentPlayers is who queued the songs that most recently started in a
// room, newest first, for fairness rules that look back a few songs. An
// autopilot song is nobody's: ”.
func (q *Queries) RecentPlayers(ctx context.Context, arg RecentPlayersParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, recentPlayers, arg.RoomID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var added_by string
		if err := rows.Scan(&added_by); err != nil {
			return nil, err
		}
		items = append(items, added_by)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseGameHolds = `-- name: ReleaseGameHolds :exec
UPDATE queue_items SET game_held = FALSE WHERE game_held
`

// ReleaseGameHolds lets every held song back into the play order: games
// live in memory, so after a restart nothing holds them.
func (q *Queries) ReleaseGameHolds(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, releaseGameHolds)
	return err
}

const removeQueueItem = `-- name: RemoveQueueItem :exec
UPDATE queue_items SET state = 'removed', removed_by = ?, resume_at = NULL, updated_at = ? WHERE id = ?
`

type RemoveQueueItemParams struct {
	RemovedBy sql.NullString
	UpdatedAt time.Time
	ID        string
}

// RemoveQueueItem takes a waiting song out of the queue, noting who did.
func (q *Queries) RemoveQueueItem(ctx context.Context, arg RemoveQueueItemParams) error {
	_, err := q.db.ExecContext(ctx, removeQueueItem, arg.RemovedBy, arg.UpdatedAt, arg.ID)
	return err
}

const restoreQueueItem = `-- name: RestoreQueueItem :exec
UPDATE queue_items SET state = 'queued', removed_by = NULL, updated_at = ? WHERE id = ? AND state = 'removed'
`

type RestoreQueueItemParams struct {
	UpdatedAt time.Time
	ID        string
}

// RestoreQueueItem puts a removed song back, in the place it had.
func (q *Queries) RestoreQueueItem(ctx context.Context, arg RestoreQueueItemParams) error {
	_, err := q.db.ExecContext(ctx, restoreQueueItem, arg.UpdatedAt, arg.ID)
	return err
}

const resumeQueueItem = `-- name: ResumeQueueItem :exec
UPDATE queue_items SET state = 'queued', resume_at = ?, updated_at = ? WHERE id = ? AND state = 'playing'
`

type ResumeQueueItemParams struct {
	ResumeAt  sql.NullTime
	UpdatedAt time.Time
	ID        string
}

// ResumeQueueItem puts the playing song back at the front of the queue,
// when someone goes back to the song before it.
func (q *Queries) ResumeQueueItem(ctx context.Context, arg ResumeQueueItemParams) error {
	_, err := q.db.ExecContext(ctx, resumeQueueItem, arg.ResumeAt, arg.UpdatedAt, arg.ID)
	return err
}

const setQueueItemState = `-- name: SetQueueItemState :exec
UPDATE queue_items SET state = ?, resume_at = NULL, front_at = NULL, game_held = FALSE, updated_at = ? WHERE id = ?
`

type SetQueueItemStateParams struct {
	State     string
	UpdatedAt time.Time
	ID        string
}

// SetQueueItemState also ends a song's place at the front of the queue,
// and a game's hold on it.
func (q *Queries) SetQueueItemState(ctx context.Context, arg SetQueueItemStateParams) error {
	_, err := q.db.ExecContext(ctx, setQueueItemState, arg.State, arg.UpdatedAt, arg.ID)
	return err
}

const setQueueItemVia = `-- name: SetQueueItemVia :exec
UPDATE queue_items SET via_provider = ?, via_link_id = ?, via_track_id = ?, updated_at = ? WHERE id = ?
`

type SetQueueItemViaParams struct {
	ViaProvider sql.NullString
	ViaLinkID   sql.NullString
	ViaTrackID  sql.NullString
	UpdatedAt   time.Time
	ID          string
}

// SetQueueItemVia records where an item plays from instead of its own link.
func (q *Queries) SetQueueItemVia(ctx context.Context, arg SetQueueItemViaParams) error {
	_, err := q.db.ExecContext(ctx, setQueueItemVia,
		arg.ViaProvider,
		arg.ViaLinkID,
		arg.ViaTrackID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setTrackPalette = `-- name: SetTrackPalette :exec
UPDATE queue_items SET palette = ?1
WHERE provider = ?2 AND track_id = ?3
  AND (state IN ('queued', 'playing') OR id = ?4)
`

type SetTrackPaletteParams struct {
	Palette  sql.NullString
	Provider string
	TrackID  string
	ItemID   string
}

// SetTrackPalette saves a song's palette on every waiting or playing item
// that's that song, and on the given item.
func (q *Queries) SetTrackPalette(ctx context.Context, arg SetTrackPaletteParams) error {
	_, err := q.db.ExecContext(ctx, setTrackPalette,
		arg.Palette,
		arg.Provider,
		arg.TrackID,
		arg.ItemID,
	)
	return err
}

const startPlay = `-- name: StartPlay :one
INSERT INTO play_history (id, room_id, queue_item_id, started_at)
VALUES (?, ?, ?, ?)
RETURNING id, room_id, queue_item_id, started_at, ended_at, end_reason
`

type StartPlayParams struct {
	ID          string
	RoomID      string
	QueueItemID string
	StartedAt   time.Time
}

func (q *Queries) StartPlay(ctx context.Context, arg StartPlayParams) (PlayHistory, error) {
	row := q.db.QueryRowContext(ctx, startPlay,
		arg.ID,
		arg.RoomID,
		arg.QueueItemID,
		arg.StartedAt,
	)
	var i PlayHistory
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.QueueItemID,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
	)
	return i, err
}
