// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queue.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const addQueueItem = `-- name: AddQueueItem :one
INSERT INTO queue_items (id, room_id, added_by, provider, link_id, track_id, metadata, lane_position, added_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?9, ?9)
RETURNING id, room_id, added_by, provider, link_id, track_id, metadata, state, lane_position, added_at, updated_at
`

type AddQueueItemParams struct {
	ID           string
	RoomID       string
	AddedBy      string
	Provider     string
	LinkID       sql.NullString
	TrackID      string
	Metadata     string
	LanePosition int64
	Now          time.Time
}

func (q *Queries) AddQueueItem(ctx context.Context, arg AddQueueItemParams) (QueueItem, error) {
	row := q.db.QueryRowContext(ctx, addQueueItem,
		arg.ID,
		arg.RoomID,
		arg.AddedBy,
		arg.Provider,
		arg.LinkID,
		arg.TrackID,
		arg.Metadata,
		arg.LanePosition,
		arg.Now,
	)
	var i QueueItem
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.AddedBy,
		&i.Provider,
		&i.LinkID,
		&i.TrackID,
		&i.Metadata,
		&i.State,
		&i.LanePosition,
		&i.AddedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const endPlay = `-- name: EndPlay :exec
UPDATE play_history SET ended_at = ?, end_reason = ? WHERE id = ? AND ended_at IS NULL
`

type EndPlayParams struct {
	EndedAt   sql.NullTime
	EndReason sql.NullString
	ID        string
}

func (q *Queries) EndPlay(ctx context.Context, arg EndPlayParams) error {
	_, err := q.db.ExecContext(ctx, endPlay, arg.EndedAt, arg.EndReason, arg.ID)
	return err
}

const getPlaying = `-- name: GetPlaying :one
SELECT id, room_id, added_by, provider, link_id, track_id, metadata, state, lane_position, added_at, updated_at FROM queue_items WHERE room_id = ? AND state = 'playing'
`

func (q *Queries) GetPlaying(ctx context.Context, roomID string) (QueueItem, error) {
	row := q.db.QueryRowContext(ctx, getPlaying, roomID)
	var i QueueItem
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.AddedBy,
		&i.Provider,
		&i.LinkID,
		&i.TrackID,
		&i.Metadata,
		&i.State,
		&i.LanePosition,
		&i.AddedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQueueItem = `-- name: GetQueueItem :one
SELECT id, room_id, added_by, provider, link_id, track_id, metadata, state, lane_position, added_at, updated_at FROM queue_items WHERE id = ?
`

func (q *Queries) GetQueueItem(ctx context.Context, id string) (QueueItem, error) {
	row := q.db.QueryRowContext(ctx, getQueueItem, id)
	var i QueueItem
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.AddedBy,
		&i.Provider,
		&i.LinkID,
		&i.TrackID,
		&i.Metadata,
		&i.State,
		&i.LanePosition,
		&i.AddedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHistory = `-- name: ListHistory :many
SELECT play_history.id, play_history.room_id, play_history.queue_item_id, play_history.started_at, play_history.ended_at, play_history.end_reason, queue_items.id, queue_items.room_id, queue_items.added_by, queue_items.provider, queue_items.link_id, queue_items.track_id, queue_items.metadata, queue_items.state, queue_items.lane_position, queue_items.added_at, queue_items.updated_at
FROM play_history
JOIN queue_items ON queue_items.id = play_history.queue_item_id
WHERE play_history.room_id = ?
ORDER BY play_history.started_at DESC
LIMIT ?
`

type ListHistoryParams struct {
	RoomID string
	Limit  int64
}

type ListHistoryRow struct {
	PlayHistory PlayHistory
	QueueItem   QueueItem
}

func (q *Queries) ListHistory(ctx context.Context, arg ListHistoryParams) ([]ListHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listHistory, arg.RoomID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHistoryRow{}
	for rows.Next() {
		var i ListHistoryRow
		if err := rows.Scan(
			&i.PlayHistory.ID,
			&i.PlayHistory.RoomID,
			&i.PlayHistory.QueueItemID,
			&i.PlayHistory.StartedAt,
			&i.PlayHistory.EndedAt,
			&i.PlayHistory.EndReason,
			&i.QueueItem.ID,
			&i.QueueItem.RoomID,
			&i.QueueItem.AddedBy,
			&i.QueueItem.Provider,
			&i.QueueItem.LinkID,
			&i.QueueItem.TrackID,
			&i.QueueItem.Metadata,
			&i.QueueItem.State,
			&i.QueueItem.LanePosition,
			&i.QueueItem.AddedAt,
			&i.QueueItem.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcoming = `-- name: ListUpcoming :many
SELECT id, room_id, added_by, provider, link_id, track_id, metadata, state, lane_position, added_at, updated_at FROM queue_items
WHERE room_id = ? AND state IN ('queued', 'playing')
ORDER BY added_by, lane_position, added_at
`

// ListUpcoming returns the playing item and queued items, each lane in
// order. The fairness engine interleaves the lanes.
func (q *Queries) ListUpcoming(ctx context.Context, roomID string) ([]QueueItem, error) {
	rows, err := q.db.QueryContext(ctx, listUpcoming, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QueueItem{}
	for rows.Next() {
		var i QueueItem
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.AddedBy,
			&i.Provider,
			&i.LinkID,
			&i.TrackID,
			&i.Metadata,
			&i.State,
			&i.LanePosition,
			&i.AddedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveQueueItem = `-- name: MoveQueueItem :exec
UPDATE queue_items SET lane_position = ?, updated_at = ? WHERE id = ? AND state = 'queued'
`

type MoveQueueItemParams struct {
	LanePosition int64
	UpdatedAt    time.Time
	ID           string
}

func (q *Queries) MoveQueueItem(ctx context.Context, arg MoveQueueItemParams) error {
	_, err := q.db.ExecContext(ctx, moveQueueItem, arg.LanePosition, arg.UpdatedAt, arg.ID)
	return err
}

const nextLanePosition = `-- name: NextLanePosition :one
SELECT CAST(coalesce(max(lane_position), 0) + 1024 AS INTEGER)
FROM queue_items
WHERE room_id = ? AND added_by = ? AND state = 'queued'
`

type NextLanePositionParams struct {
	RoomID  string
	AddedBy string
}

// NextLanePosition is where a new item goes at the end of a user's lane.
func (q *Queries) NextLanePosition(ctx context.Context, arg NextLanePositionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextLanePosition, arg.RoomID, arg.AddedBy)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const setQueueItemState = `-- name: SetQueueItemState :exec
UPDATE queue_items SET state = ?, updated_at = ? WHERE id = ?
`

type SetQueueItemStateParams struct {
	State     string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) SetQueueItemState(ctx context.Context, arg SetQueueItemStateParams) error {
	_, err := q.db.ExecContext(ctx, setQueueItemState, arg.State, arg.UpdatedAt, arg.ID)
	return err
}

const startPlay = `-- name: StartPlay :one
INSERT INTO play_history (id, room_id, queue_item_id, started_at)
VALUES (?, ?, ?, ?)
RETURNING id, room_id, queue_item_id, started_at, ended_at, end_reason
`

type StartPlayParams struct {
	ID          string
	RoomID      string
	QueueItemID string
	StartedAt   time.Time
}

func (q *Queries) StartPlay(ctx context.Context, arg StartPlayParams) (PlayHistory, error) {
	row := q.db.QueryRowContext(ctx, startPlay,
		arg.ID,
		arg.RoomID,
		arg.QueueItemID,
		arg.StartedAt,
	)
	var i PlayHistory
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.QueueItemID,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
	)
	return i, err
}
