// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reset_links.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const createResetLink = `-- name: CreateResetLink :one
INSERT INTO reset_links (id, code_hash, user_id, created_by, created_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, code_hash, user_id, created_by, created_at, expires_at
`

type CreateResetLinkParams struct {
	ID        string
	CodeHash  []byte
	UserID    string
	CreatedBy sql.NullString
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) CreateResetLink(ctx context.Context, arg CreateResetLinkParams) (ResetLink, error) {
	row := q.db.QueryRowContext(ctx, createResetLink,
		arg.ID,
		arg.CodeHash,
		arg.UserID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i ResetLink
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.UserID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredResetLinks = `-- name: DeleteExpiredResetLinks :exec
DELETE FROM reset_links WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredResetLinks(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredResetLinks, expiresAt)
	return err
}

const deleteResetLink = `-- name: DeleteResetLink :execrows
DELETE FROM reset_links WHERE id = ?
`

func (q *Queries) DeleteResetLink(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteResetLink, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUserResetLinks = `-- name: DeleteUserResetLinks :execrows
DELETE FROM reset_links WHERE user_id = ?
`

func (q *Queries) DeleteUserResetLinks(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUserResetLinks, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getResetLink = `-- name: GetResetLink :one
SELECT id, code_hash, user_id, created_by, created_at, expires_at FROM reset_links WHERE code_hash = ?1 AND expires_at > ?2
`

type GetResetLinkParams struct {
	CodeHash []byte
	Now      time.Time
}

// GetResetLink returns an unexpired link.
func (q *Queries) GetResetLink(ctx context.Context, arg GetResetLinkParams) (ResetLink, error) {
	row := q.db.QueryRowContext(ctx, getResetLink, arg.CodeHash, arg.Now)
	var i ResetLink
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.UserID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listResetLinks = `-- name: ListResetLinks :many
SELECT id, code_hash, user_id, created_by, created_at, expires_at FROM reset_links WHERE expires_at > ?1 ORDER BY created_at DESC
`

// ListResetLinks returns unexpired links, newest first.
func (q *Queries) ListResetLinks(ctx context.Context, now time.Time) ([]ResetLink, error) {
	rows, err := q.db.QueryContext(ctx, listResetLinks, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResetLink{}
	for rows.Next() {
		var i ResetLink
		if err := rows.Scan(
			&i.ID,
			&i.CodeHash,
			&i.UserID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const useResetLink = `-- name: UseResetLink :execrows
DELETE FROM reset_links WHERE id = ?1 AND expires_at > ?2
`

type UseResetLinkParams struct {
	ID  string
	Now time.Time
}

// UseResetLink deletes a link if it's still good. 0 rows means it isn't.
func (q *Queries) UseResetLink(ctx context.Context, arg UseResetLinkParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, useResetLink, arg.ID, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
