// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const bumpQueueVersion = `-- name: BumpQueueVersion :one
UPDATE rooms SET queue_version = queue_version + 1 WHERE id = ? RETURNING queue_version
`

// BumpQueueVersion records a queue change and returns the new version.
func (q *Queries) BumpQueueVersion(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, bumpQueueVersion, id)
	var queue_version int64
	err := row.Scan(&queue_version)
	return queue_version, err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (id, name, owner_id, fairness_mode, settings, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, owner_id, player_device_id, fairness_mode, settings, created_at, queue_version, visibility
`

type CreateRoomParams struct {
	ID           string
	Name         string
	OwnerID      string
	FairnessMode string
	Settings     string
	CreatedAt    time.Time
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, createRoom,
		arg.ID,
		arg.Name,
		arg.OwnerID,
		arg.FairnessMode,
		arg.Settings,
		arg.CreatedAt,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.PlayerDeviceID,
		&i.FairnessMode,
		&i.Settings,
		&i.CreatedAt,
		&i.QueueVersion,
		&i.Visibility,
	)
	return i, err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms WHERE id = ?
`

func (q *Queries) DeleteRoom(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRoom, id)
	return err
}

const getRoom = `-- name: GetRoom :one
SELECT id, name, owner_id, player_device_id, fairness_mode, settings, created_at, queue_version, visibility FROM rooms WHERE id = ?
`

func (q *Queries) GetRoom(ctx context.Context, id string) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.PlayerDeviceID,
		&i.FairnessMode,
		&i.Settings,
		&i.CreatedAt,
		&i.QueueVersion,
		&i.Visibility,
	)
	return i, err
}

const listRooms = `-- name: ListRooms :many
SELECT id, name, owner_id, player_device_id, fairness_mode, settings, created_at, queue_version, visibility FROM rooms ORDER BY created_at
`

func (q *Queries) ListRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.PlayerDeviceID,
			&i.FairnessMode,
			&i.Settings,
			&i.CreatedAt,
			&i.QueueVersion,
			&i.Visibility,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRoomOwner = `-- name: SetRoomOwner :one
UPDATE rooms SET owner_id = ? WHERE id = ?
RETURNING id, name, owner_id, player_device_id, fairness_mode, settings, created_at, queue_version, visibility
`

type SetRoomOwnerParams struct {
	OwnerID string
	ID      string
}

func (q *Queries) SetRoomOwner(ctx context.Context, arg SetRoomOwnerParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, setRoomOwner, arg.OwnerID, arg.ID)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.PlayerDeviceID,
		&i.FairnessMode,
		&i.Settings,
		&i.CreatedAt,
		&i.QueueVersion,
		&i.Visibility,
	)
	return i, err
}

const setRoomPlayer = `-- name: SetRoomPlayer :exec
UPDATE rooms SET player_device_id = ? WHERE id = ?
`

type SetRoomPlayerParams struct {
	PlayerDeviceID sql.NullString
	ID             string
}

func (q *Queries) SetRoomPlayer(ctx context.Context, arg SetRoomPlayerParams) error {
	_, err := q.db.ExecContext(ctx, setRoomPlayer, arg.PlayerDeviceID, arg.ID)
	return err
}

const transferRooms = `-- name: TransferRooms :many
UPDATE rooms SET owner_id = ?1 WHERE owner_id = ?2
RETURNING id, name, owner_id, player_device_id, fairness_mode, settings, created_at, queue_version, visibility
`

type TransferRoomsParams struct {
	ToID   string
	FromID string
}

// TransferRooms hands every room one user owns to another, and returns them.
func (q *Queries) TransferRooms(ctx context.Context, arg TransferRoomsParams) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, transferRooms, arg.ToID, arg.FromID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.PlayerDeviceID,
			&i.FairnessMode,
			&i.Settings,
			&i.CreatedAt,
			&i.QueueVersion,
			&i.Visibility,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms SET name = ?, fairness_mode = ?, settings = ?
WHERE id = ?
RETURNING id, name, owner_id, player_device_id, fairness_mode, settings, created_at, queue_version, visibility
`

type UpdateRoomParams struct {
	Name         string
	FairnessMode string
	Settings     string
	ID           string
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, updateRoom,
		arg.Name,
		arg.FairnessMode,
		arg.Settings,
		arg.ID,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.PlayerDeviceID,
		&i.FairnessMode,
		&i.Settings,
		&i.CreatedAt,
		&i.QueueVersion,
		&i.Visibility,
	)
	return i, err
}
