// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: room_access.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const addRoomMember = `-- name: AddRoomMember :exec
INSERT INTO room_members (room_id, user_id, status, added_by, created_at)
VALUES (?, ?, 'member', ?, ?)
ON CONFLICT (room_id, user_id) DO UPDATE SET status = 'member', added_by = excluded.added_by, created_at = excluded.created_at
WHERE room_members.status = 'pending'
`

type AddRoomMemberParams struct {
	RoomID    string
	UserID    string
	AddedBy   sql.NullString
	CreatedAt time.Time
}

// AddRoomMember lets someone into a room, or approves their request.
func (q *Queries) AddRoomMember(ctx context.Context, arg AddRoomMemberParams) error {
	_, err := q.db.ExecContext(ctx, addRoomMember,
		arg.RoomID,
		arg.UserID,
		arg.AddedBy,
		arg.CreatedAt,
	)
	return err
}

const createRoomInvite = `-- name: CreateRoomInvite :one
INSERT INTO room_invites (code, room_id, created_by, created_at, expires_at, max_uses)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING code, room_id, created_by, created_at, expires_at, max_uses, uses
`

type CreateRoomInviteParams struct {
	Code      string
	RoomID    string
	CreatedBy sql.NullString
	CreatedAt time.Time
	ExpiresAt sql.NullTime
	MaxUses   sql.NullInt64
}

func (q *Queries) CreateRoomInvite(ctx context.Context, arg CreateRoomInviteParams) (RoomInvite, error) {
	row := q.db.QueryRowContext(ctx, createRoomInvite,
		arg.Code,
		arg.RoomID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.MaxUses,
	)
	var i RoomInvite
	err := row.Scan(
		&i.Code,
		&i.RoomID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.Uses,
	)
	return i, err
}

const deleteRoomInvite = `-- name: DeleteRoomInvite :execrows
DELETE FROM room_invites WHERE room_id = ? AND code = ?
`

type DeleteRoomInviteParams struct {
	RoomID string
	Code   string
}

func (q *Queries) DeleteRoomInvite(ctx context.Context, arg DeleteRoomInviteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRoomInvite, arg.RoomID, arg.Code)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRoomInvites = `-- name: DeleteRoomInvites :exec
DELETE FROM room_invites WHERE room_id = ?
`

func (q *Queries) DeleteRoomInvites(ctx context.Context, roomID string) error {
	_, err := q.db.ExecContext(ctx, deleteRoomInvites, roomID)
	return err
}

const deleteSpentRoomInvites = `-- name: DeleteSpentRoomInvites :exec
DELETE FROM room_invites
WHERE (expires_at IS NOT NULL AND expires_at <= ?1)
   OR (max_uses IS NOT NULL AND uses >= max_uses)
`

func (q *Queries) DeleteSpentRoomInvites(ctx context.Context, now sql.NullTime) error {
	_, err := q.db.ExecContext(ctx, deleteSpentRoomInvites, now)
	return err
}

const getRoomInvite = `-- name: GetRoomInvite :one
SELECT code, room_id, created_by, created_at, expires_at, max_uses, uses FROM room_invites WHERE code = ?
`

func (q *Queries) GetRoomInvite(ctx context.Context, code string) (RoomInvite, error) {
	row := q.db.QueryRowContext(ctx, getRoomInvite, code)
	var i RoomInvite
	err := row.Scan(
		&i.Code,
		&i.RoomID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.Uses,
	)
	return i, err
}

const getRoomMember = `-- name: GetRoomMember :one
SELECT room_id, user_id, status, added_by, created_at FROM room_members WHERE room_id = ? AND user_id = ?
`

type GetRoomMemberParams struct {
	RoomID string
	UserID string
}

func (q *Queries) GetRoomMember(ctx context.Context, arg GetRoomMemberParams) (RoomMember, error) {
	row := q.db.QueryRowContext(ctx, getRoomMember, arg.RoomID, arg.UserID)
	var i RoomMember
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Status,
		&i.AddedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listRoomInvites = `-- name: ListRoomInvites :many
SELECT code, room_id, created_by, created_at, expires_at, max_uses, uses FROM room_invites
WHERE room_id = ?1
  AND (expires_at IS NULL OR expires_at > ?2)
  AND (max_uses IS NULL OR uses < max_uses)
ORDER BY created_at DESC, code
`

type ListRoomInvitesParams struct {
	RoomID string
	Now    sql.NullTime
}

// ListRoomInvites lists a room's invites that still work, newest first.
func (q *Queries) ListRoomInvites(ctx context.Context, arg ListRoomInvitesParams) ([]RoomInvite, error) {
	rows, err := q.db.QueryContext(ctx, listRoomInvites, arg.RoomID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomInvite{}
	for rows.Next() {
		var i RoomInvite
		if err := rows.Scan(
			&i.Code,
			&i.RoomID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.MaxUses,
			&i.Uses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomMembers = `-- name: ListRoomMembers :many
SELECT room_id, user_id, status, added_by, created_at FROM room_members WHERE room_id = ? ORDER BY created_at, user_id
`

func (q *Queries) ListRoomMembers(ctx context.Context, roomID string) ([]RoomMember, error) {
	rows, err := q.db.QueryContext(ctx, listRoomMembers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomMember{}
	for rows.Next() {
		var i RoomMember
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.Status,
			&i.AddedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const memberRoomIDs = `-- name: MemberRoomIDs :many
SELECT room_id FROM room_members WHERE user_id = ? AND status = 'member'
`

// MemberRoomIDs are the rooms someone is a member of (not just asked).
func (q *Queries) MemberRoomIDs(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, memberRoomIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var room_id string
		if err := rows.Scan(&room_id); err != nil {
			return nil, err
		}
		items = append(items, room_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoomMember = `-- name: RemoveRoomMember :execrows
DELETE FROM room_members WHERE room_id = ? AND user_id = ?
`

type RemoveRoomMemberParams struct {
	RoomID string
	UserID string
}

func (q *Queries) RemoveRoomMember(ctx context.Context, arg RemoveRoomMemberParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeRoomMember, arg.RoomID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const requestRoomMembership = `-- name: RequestRoomMembership :execrows
INSERT INTO room_members (room_id, user_id, status, created_at)
VALUES (?, ?, 'pending', ?)
ON CONFLICT (room_id, user_id) DO NOTHING
`

type RequestRoomMembershipParams struct {
	RoomID    string
	UserID    string
	CreatedAt time.Time
}

// RequestRoomMembership asks to join; a member stays a member. It returns
// how many rows it added: 0 if they'd already asked, or are in.
func (q *Queries) RequestRoomMembership(ctx context.Context, arg RequestRoomMembershipParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, requestRoomMembership, arg.RoomID, arg.UserID, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setRoomVisibility = `-- name: SetRoomVisibility :one
UPDATE rooms SET visibility = ? WHERE id = ?
RETURNING id, name, owner_id, player_device_id, fairness_mode, settings, created_at, queue_version, visibility
`

type SetRoomVisibilityParams struct {
	Visibility string
	ID         string
}

func (q *Queries) SetRoomVisibility(ctx context.Context, arg SetRoomVisibilityParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, setRoomVisibility, arg.Visibility, arg.ID)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.PlayerDeviceID,
		&i.FairnessMode,
		&i.Settings,
		&i.CreatedAt,
		&i.QueueVersion,
		&i.Visibility,
	)
	return i, err
}

const useRoomInvite = `-- name: UseRoomInvite :one
UPDATE room_invites SET uses = uses + 1
WHERE code = ?1
  AND (expires_at IS NULL OR expires_at > ?2)
  AND (max_uses IS NULL OR uses < max_uses)
RETURNING code, room_id, created_by, created_at, expires_at, max_uses, uses
`

type UseRoomInviteParams struct {
	Code string
	Now  sql.NullTime
}

// UseRoomInvite counts a use of an invite that still works.
func (q *Queries) UseRoomInvite(ctx context.Context, arg UseRoomInviteParams) (RoomInvite, error) {
	row := q.db.QueryRowContext(ctx, useRoomInvite, arg.Code, arg.Now)
	var i RoomInvite
	err := row.Scan(
		&i.Code,
		&i.RoomID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.Uses,
	)
	return i, err
}
