// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service_links.sql

package store

import (
	"context"
	"strings"
	"time"
)

const createServiceLink = `-- name: CreateServiceLink :one

INSERT INTO service_links (id, user_id, provider, account_id, account_label, encrypted_credentials, created_at, updated_at, last_ok_at)
VALUES (?, ?, ?, ?, ?, ?, ?7, ?7, ?7)
RETURNING id, user_id, provider, account_id, account_label, encrypted_credentials, status, status_detail, created_at, updated_at, last_ok_at, shared
`

type CreateServiceLinkParams struct {
	ID                   string
	UserID               string
	Provider             string
	AccountID            string
	AccountLabel         string
	EncryptedCredentials []byte
	Now                  time.Time
}

// Queries that repeat a sqlc.arg must name every parameter: sqlc numbers
// repeated args (?N), and a plain ? after one would get the wrong index.
func (q *Queries) CreateServiceLink(ctx context.Context, arg CreateServiceLinkParams) (ServiceLink, error) {
	row := q.db.QueryRowContext(ctx, createServiceLink,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.AccountID,
		arg.AccountLabel,
		arg.EncryptedCredentials,
		arg.Now,
	)
	var i ServiceLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.AccountID,
		&i.AccountLabel,
		&i.EncryptedCredentials,
		&i.Status,
		&i.StatusDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastOkAt,
		&i.Shared,
	)
	return i, err
}

const deleteServiceLink = `-- name: DeleteServiceLink :exec
DELETE FROM service_links WHERE id = ? AND user_id = ?
`

type DeleteServiceLinkParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteServiceLink(ctx context.Context, arg DeleteServiceLinkParams) error {
	_, err := q.db.ExecContext(ctx, deleteServiceLink, arg.ID, arg.UserID)
	return err
}

const findServiceLink = `-- name: FindServiceLink :one
SELECT id, user_id, provider, account_id, account_label, encrypted_credentials, status, status_detail, created_at, updated_at, last_ok_at, shared FROM service_links WHERE user_id = ? AND provider = ? AND account_id = ?
`

type FindServiceLinkParams struct {
	UserID    string
	Provider  string
	AccountID string
}

func (q *Queries) FindServiceLink(ctx context.Context, arg FindServiceLinkParams) (ServiceLink, error) {
	row := q.db.QueryRowContext(ctx, findServiceLink, arg.UserID, arg.Provider, arg.AccountID)
	var i ServiceLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.AccountID,
		&i.AccountLabel,
		&i.EncryptedCredentials,
		&i.Status,
		&i.StatusDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastOkAt,
		&i.Shared,
	)
	return i, err
}

const getServiceLink = `-- name: GetServiceLink :one
SELECT id, user_id, provider, account_id, account_label, encrypted_credentials, status, status_detail, created_at, updated_at, last_ok_at, shared FROM service_links WHERE id = ?
`

func (q *Queries) GetServiceLink(ctx context.Context, id string) (ServiceLink, error) {
	row := q.db.QueryRowContext(ctx, getServiceLink, id)
	var i ServiceLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.AccountID,
		&i.AccountLabel,
		&i.EncryptedCredentials,
		&i.Status,
		&i.StatusDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastOkAt,
		&i.Shared,
	)
	return i, err
}

const getUsableServiceLink = `-- name: GetUsableServiceLink :one
SELECT id, user_id, provider, account_id, account_label, encrypted_credentials, status, status_detail, created_at, updated_at, last_ok_at, shared FROM service_links WHERE id = ?1 AND (user_id = ?2 OR shared)
`

type GetUsableServiceLinkParams struct {
	ID     string
	UserID string
}

// GetUsableServiceLink is one link user_id may use: their own, or shared.
func (q *Queries) GetUsableServiceLink(ctx context.Context, arg GetUsableServiceLinkParams) (ServiceLink, error) {
	row := q.db.QueryRowContext(ctx, getUsableServiceLink, arg.ID, arg.UserID)
	var i ServiceLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.AccountID,
		&i.AccountLabel,
		&i.EncryptedCredentials,
		&i.Status,
		&i.StatusDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastOkAt,
		&i.Shared,
	)
	return i, err
}

const getUserServiceLink = `-- name: GetUserServiceLink :one
SELECT id, user_id, provider, account_id, account_label, encrypted_credentials, status, status_detail, created_at, updated_at, last_ok_at, shared FROM service_links WHERE id = ? AND user_id = ?
`

type GetUserServiceLinkParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetUserServiceLink(ctx context.Context, arg GetUserServiceLinkParams) (ServiceLink, error) {
	row := q.db.QueryRowContext(ctx, getUserServiceLink, arg.ID, arg.UserID)
	var i ServiceLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.AccountID,
		&i.AccountLabel,
		&i.EncryptedCredentials,
		&i.Status,
		&i.StatusDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastOkAt,
		&i.Shared,
	)
	return i, err
}

const listAllServiceLinks = `-- name: ListAllServiceLinks :many
SELECT id, user_id, provider, account_id, account_label, encrypted_credentials, status, status_detail, created_at, updated_at, last_ok_at, shared FROM service_links ORDER BY id
`

func (q *Queries) ListAllServiceLinks(ctx context.Context) ([]ServiceLink, error) {
	rows, err := q.db.QueryContext(ctx, listAllServiceLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceLink{}
	for rows.Next() {
		var i ServiceLink
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.AccountID,
			&i.AccountLabel,
			&i.EncryptedCredentials,
			&i.Status,
			&i.StatusDetail,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastOkAt,
			&i.Shared,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchLinks = `-- name: ListMatchLinks :many
SELECT id, user_id, provider, account_id, account_label, encrypted_credentials, status, status_detail, created_at, updated_at, last_ok_at, shared FROM service_links
WHERE status != 'expired' AND (shared OR user_id IN (/*SLICE:user_ids*/?))
ORDER BY shared, created_at
`

// ListMatchLinks returns the links a room may look for a song on: those
// of the given users (who are in the room) and shared ones, unless
// expired. The users' own links come first.
func (q *Queries) ListMatchLinks(ctx context.Context, userIds []string) ([]ServiceLink, error) {
	query := listMatchLinks
	var queryParams []interface{}
	if len(userIds) > 0 {
		for _, v := range userIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:user_ids*/?", strings.Repeat(",?", len(userIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:user_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceLink{}
	for rows.Next() {
		var i ServiceLink
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.AccountID,
			&i.AccountLabel,
			&i.EncryptedCredentials,
			&i.Status,
			&i.StatusDetail,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastOkAt,
			&i.Shared,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceLinks = `-- name: ListServiceLinks :many
SELECT id, user_id, provider, account_id, account_label, encrypted_credentials, status, status_detail, created_at, updated_at, last_ok_at, shared FROM service_links WHERE user_id = ? ORDER BY created_at
`

func (q *Queries) ListServiceLinks(ctx context.Context, userID string) ([]ServiceLink, error) {
	rows, err := q.db.QueryContext(ctx, listServiceLinks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceLink{}
	for rows.Next() {
		var i ServiceLink
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.AccountID,
			&i.AccountLabel,
			&i.EncryptedCredentials,
			&i.Status,
			&i.StatusDetail,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastOkAt,
			&i.Shared,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsableServiceLinks = `-- name: ListUsableServiceLinks :many
SELECT id, user_id, provider, account_id, account_label, encrypted_credentials, status, status_detail, created_at, updated_at, last_ok_at, shared FROM service_links
WHERE user_id = ?1 OR shared
ORDER BY user_id != ?1, created_at
`

// ListUsableServiceLinks is every link user_id can search and queue from:
// their own first, then everyone else's shared ones. (sqlc doesn't rewrite
// sqlc.arg in ORDER BY, so the second use is ?1, the same parameter.)
func (q *Queries) ListUsableServiceLinks(ctx context.Context, userID string) ([]ServiceLink, error) {
	rows, err := q.db.QueryContext(ctx, listUsableServiceLinks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceLink{}
	for rows.Next() {
		var i ServiceLink
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.AccountID,
			&i.AccountLabel,
			&i.EncryptedCredentials,
			&i.Status,
			&i.StatusDetail,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastOkAt,
			&i.Shared,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markServiceLinkOK = `-- name: MarkServiceLinkOK :exec
UPDATE service_links SET status = 'ok', status_detail = '', updated_at = ?1, last_ok_at = ?1 WHERE id = ?2
`

type MarkServiceLinkOKParams struct {
	Now time.Time
	ID  string
}

func (q *Queries) MarkServiceLinkOK(ctx context.Context, arg MarkServiceLinkOKParams) error {
	_, err := q.db.ExecContext(ctx, markServiceLinkOK, arg.Now, arg.ID)
	return err
}

const relinkServiceLink = `-- name: RelinkServiceLink :exec
UPDATE service_links
SET encrypted_credentials = ?1, account_label = ?2, status = 'ok', status_detail = '',
    updated_at = ?3, last_ok_at = ?3
WHERE id = ?4
`

type RelinkServiceLinkParams struct {
	EncryptedCredentials []byte
	AccountLabel         string
	Now                  time.Time
	ID                   string
}

// RelinkServiceLink stores fresh credentials from linking again.
func (q *Queries) RelinkServiceLink(ctx context.Context, arg RelinkServiceLinkParams) error {
	_, err := q.db.ExecContext(ctx, relinkServiceLink,
		arg.EncryptedCredentials,
		arg.AccountLabel,
		arg.Now,
		arg.ID,
	)
	return err
}

const rewrapServiceLink = `-- name: RewrapServiceLink :exec
UPDATE service_links SET encrypted_credentials = ? WHERE id = ?
`

type RewrapServiceLinkParams struct {
	EncryptedCredentials []byte
	ID                   string
}

// RewrapServiceLink replaces the ciphertext only (vault key rotation).
func (q *Queries) RewrapServiceLink(ctx context.Context, arg RewrapServiceLinkParams) error {
	_, err := q.db.ExecContext(ctx, rewrapServiceLink, arg.EncryptedCredentials, arg.ID)
	return err
}

const setServiceLinkShared = `-- name: SetServiceLinkShared :exec
UPDATE service_links SET shared = ?, updated_at = ? WHERE id = ? AND user_id = ?
`

type SetServiceLinkSharedParams struct {
	Shared    bool
	UpdatedAt time.Time
	ID        string
	UserID    string
}

func (q *Queries) SetServiceLinkShared(ctx context.Context, arg SetServiceLinkSharedParams) error {
	_, err := q.db.ExecContext(ctx, setServiceLinkShared,
		arg.Shared,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	return err
}

const setServiceLinkStatus = `-- name: SetServiceLinkStatus :exec
UPDATE service_links SET status = ?, status_detail = ?, updated_at = ? WHERE id = ?
`

type SetServiceLinkStatusParams struct {
	Status       string
	StatusDetail string
	UpdatedAt    time.Time
	ID           string
}

func (q *Queries) SetServiceLinkStatus(ctx context.Context, arg SetServiceLinkStatusParams) error {
	_, err := q.db.ExecContext(ctx, setServiceLinkStatus,
		arg.Status,
		arg.StatusDetail,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateServiceLinkCredentials = `-- name: UpdateServiceLinkCredentials :exec
UPDATE service_links
SET encrypted_credentials = ?1, status = 'ok', status_detail = '', updated_at = ?2, last_ok_at = ?2
WHERE id = ?3
`

type UpdateServiceLinkCredentialsParams struct {
	EncryptedCredentials []byte
	Now                  time.Time
	ID                   string
}

// UpdateServiceLinkCredentials saves re-sealed or rotated credentials and
// marks the link healthy.
func (q *Queries) UpdateServiceLinkCredentials(ctx context.Context, arg UpdateServiceLinkCredentialsParams) error {
	_, err := q.db.ExecContext(ctx, updateServiceLinkCredentials, arg.EncryptedCredentials, arg.Now, arg.ID)
	return err
}
