// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service_links.sql

package store

import (
	"context"
	"time"
)

const createServiceLink = `-- name: CreateServiceLink :one
INSERT INTO service_links (id, user_id, provider, account_id, account_label, encrypted_credentials, created_at, updated_at, last_ok_at)
VALUES (?, ?, ?, ?, ?, ?, ?7, ?7, ?7)
RETURNING id, user_id, provider, account_id, account_label, encrypted_credentials, status, status_detail, created_at, updated_at, last_ok_at
`

type CreateServiceLinkParams struct {
	ID                   string
	UserID               string
	Provider             string
	AccountID            string
	AccountLabel         string
	EncryptedCredentials []byte
	Now                  time.Time
}

func (q *Queries) CreateServiceLink(ctx context.Context, arg CreateServiceLinkParams) (ServiceLink, error) {
	row := q.db.QueryRowContext(ctx, createServiceLink,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.AccountID,
		arg.AccountLabel,
		arg.EncryptedCredentials,
		arg.Now,
	)
	var i ServiceLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.AccountID,
		&i.AccountLabel,
		&i.EncryptedCredentials,
		&i.Status,
		&i.StatusDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastOkAt,
	)
	return i, err
}

const deleteServiceLink = `-- name: DeleteServiceLink :exec
DELETE FROM service_links WHERE id = ? AND user_id = ?
`

type DeleteServiceLinkParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteServiceLink(ctx context.Context, arg DeleteServiceLinkParams) error {
	_, err := q.db.ExecContext(ctx, deleteServiceLink, arg.ID, arg.UserID)
	return err
}

const getServiceLink = `-- name: GetServiceLink :one
SELECT id, user_id, provider, account_id, account_label, encrypted_credentials, status, status_detail, created_at, updated_at, last_ok_at FROM service_links WHERE id = ?
`

func (q *Queries) GetServiceLink(ctx context.Context, id string) (ServiceLink, error) {
	row := q.db.QueryRowContext(ctx, getServiceLink, id)
	var i ServiceLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.AccountID,
		&i.AccountLabel,
		&i.EncryptedCredentials,
		&i.Status,
		&i.StatusDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastOkAt,
	)
	return i, err
}

const listServiceLinks = `-- name: ListServiceLinks :many
SELECT id, user_id, provider, account_id, account_label, encrypted_credentials, status, status_detail, created_at, updated_at, last_ok_at FROM service_links WHERE user_id = ? ORDER BY created_at
`

func (q *Queries) ListServiceLinks(ctx context.Context, userID string) ([]ServiceLink, error) {
	rows, err := q.db.QueryContext(ctx, listServiceLinks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceLink{}
	for rows.Next() {
		var i ServiceLink
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.AccountID,
			&i.AccountLabel,
			&i.EncryptedCredentials,
			&i.Status,
			&i.StatusDetail,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastOkAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markServiceLinkOK = `-- name: MarkServiceLinkOK :exec
UPDATE service_links SET status = 'ok', status_detail = '', updated_at = ?2, last_ok_at = ?2 WHERE id = ?
`

type MarkServiceLinkOKParams struct {
	Now time.Time
	ID  string
}

func (q *Queries) MarkServiceLinkOK(ctx context.Context, arg MarkServiceLinkOKParams) error {
	_, err := q.db.ExecContext(ctx, markServiceLinkOK, arg.Now, arg.ID)
	return err
}

const setServiceLinkStatus = `-- name: SetServiceLinkStatus :exec
UPDATE service_links SET status = ?, status_detail = ?, updated_at = ? WHERE id = ?
`

type SetServiceLinkStatusParams struct {
	Status       string
	StatusDetail string
	UpdatedAt    time.Time
	ID           string
}

func (q *Queries) SetServiceLinkStatus(ctx context.Context, arg SetServiceLinkStatusParams) error {
	_, err := q.db.ExecContext(ctx, setServiceLinkStatus,
		arg.Status,
		arg.StatusDetail,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateServiceLinkCredentials = `-- name: UpdateServiceLinkCredentials :exec
UPDATE service_links
SET encrypted_credentials = ?, status = 'ok', status_detail = '', updated_at = ?3, last_ok_at = ?3
WHERE id = ?
`

type UpdateServiceLinkCredentialsParams struct {
	EncryptedCredentials []byte
	Now                  time.Time
	ID                   string
}

// UpdateServiceLinkCredentials saves re-sealed or rotated credentials and
// marks the link healthy.
func (q *Queries) UpdateServiceLinkCredentials(ctx context.Context, arg UpdateServiceLinkCredentialsParams) error {
	_, err := q.db.ExecContext(ctx, updateServiceLinkCredentials, arg.EncryptedCredentials, arg.Now, arg.ID)
	return err
}
