// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: server.sql

package store

import (
	"context"
)

const getServerSettings = `-- name: GetServerSettings :one
SELECT settings FROM server_settings WHERE id = 1
`

func (q *Queries) GetServerSettings(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getServerSettings)
	var settings string
	err := row.Scan(&settings)
	return settings, err
}

const setServerSettings = `-- name: SetServerSettings :exec
INSERT INTO server_settings (id, settings) VALUES (1, ?)
ON CONFLICT (id) DO UPDATE SET settings = excluded.settings
`

func (q *Queries) SetServerSettings(ctx context.Context, settings string) error {
	_, err := q.db.ExecContext(ctx, setServerSettings, settings)
	return err
}
