/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TvRouteImport } from './routes/tv'
import { Route as AppAuthedRouteImport } from './routes/_app/_authed'
import { Route as AppDesignRouteImport } from './routes/_app/design'
import { Route as InviteCodeRouteImport } from './routes/invite.$code'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as AppAuthedIndexRouteImport } from './routes/_app/_authed/index'
import { Route as AppAuthedHistoryRouteImport } from './routes/_app/_authed/history'
import { Route as AppAuthedMeRouteImport } from './routes/_app/_authed/me'
import { Route as AppAuthedRoomRouteImport } from './routes/_app/_authed/room'
import { Route as AppAuthedSearchRouteImport } from './routes/_app/_authed/search'
import { Route as AppAuthedSettingsPeopleRouteImport } from './routes/_app/_authed/settings.people'
import { Route as AppAuthedSettingsProfileRouteImport } from './routes/_app/_authed/settings.profile'
import { Route as AppAuthedSettingsSecurityRouteImport } from './routes/_app/_authed/settings.security'
import { Route as AppAuthedSettingsServicesRouteImport } from './routes/_app/_authed/settings.services'
import { Route as AppAuthedAlbumLinkIdAlbumIdRouteImport } from './routes/_app/_authed/album.$linkId.$albumId'
import { Route as AppAuthedArtistLinkIdArtistIdRouteImport } from './routes/_app/_authed/artist.$linkId.$artistId'
import { Route as AppAuthedPlaylistLinkIdPlaylistIdRouteImport } from './routes/_app/_authed/playlist.$linkId.$playlistId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthedRoute = AppAuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => AppRoute,
} as any)
const AppDesignRoute = AppDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => AppRoute,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthedIndexRoute = AppAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedHistoryRoute = AppAuthedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedMeRoute = AppAuthedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedRoomRoute = AppAuthedRoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedSearchRoute = AppAuthedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedSettingsPeopleRoute = AppAuthedSettingsPeopleRouteImport.update({
  id: '/settings/people',
  path: '/settings/people',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedSettingsProfileRoute =
  AppAuthedSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AppAuthedRoute,
  } as any)
const AppAuthedSettingsSecurityRoute =
  AppAuthedSettingsSecurityRouteImport.update({
    id: '/settings/security',
    path: '/settings/security',
    getParentRoute: () => AppAuthedRoute,
  } as any)
const AppAuthedSettingsServicesRoute =
  AppAuthedSettingsServicesRouteImport.update({
    id: '/settings/services',
    path: '/settings/services',
    getParentRoute: () => AppAuthedRoute,
  } as any)
const AppAuthedAlbumLinkIdAlbumIdRoute =
  AppAuthedAlbumLinkIdAlbumIdRouteImport.update({
    id: '/album/$linkId/$albumId',
    path: '/album/$linkId/$albumId',
    getParentRoute: () => AppAuthedRoute,
  } as any)
const AppAuthedArtistLinkIdArtistIdRoute =
  AppAuthedArtistLinkIdArtistIdRouteImport.update({
    id: '/artist/$linkId/$artistId',
    path: '/artist/$linkId/$artistId',
    getParentRoute: () => AppAuthedRoute,
  } as any)
const AppAuthedPlaylistLinkIdPlaylistIdRoute =
  AppAuthedPlaylistLinkIdPlaylistIdRouteImport.update({
    id: '/playlist/$linkId/$playlistId',
    path: '/playlist/$linkId/$playlistId',
    getParentRoute: () => AppAuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppAuthedIndexRoute
  '/login': typeof LoginRoute
  '/tv': typeof TvRoute
  '/design': typeof AppDesignRoute
  '/invite/$code': typeof InviteCodeRoute
  '/join/$token': typeof JoinTokenRoute
  '/history': typeof AppAuthedHistoryRoute
  '/me': typeof AppAuthedMeRoute
  '/room': typeof AppAuthedRoomRoute
  '/search': typeof AppAuthedSearchRoute
  '/settings/people': typeof AppAuthedSettingsPeopleRoute
  '/settings/profile': typeof AppAuthedSettingsProfileRoute
  '/settings/security': typeof AppAuthedSettingsSecurityRoute
  '/settings/services': typeof AppAuthedSettingsServicesRoute
  '/album/$linkId/$albumId': typeof AppAuthedAlbumLinkIdAlbumIdRoute
  '/artist/$linkId/$artistId': typeof AppAuthedArtistLinkIdArtistIdRoute
  '/playlist/$linkId/$playlistId': typeof AppAuthedPlaylistLinkIdPlaylistIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppAuthedIndexRoute
  '/login': typeof LoginRoute
  '/tv': typeof TvRoute
  '/design': typeof AppDesignRoute
  '/invite/$code': typeof InviteCodeRoute
  '/join/$token': typeof JoinTokenRoute
  '/history': typeof AppAuthedHistoryRoute
  '/me': typeof AppAuthedMeRoute
  '/room': typeof AppAuthedRoomRoute
  '/search': typeof AppAuthedSearchRoute
  '/settings/people': typeof AppAuthedSettingsPeopleRoute
  '/settings/profile': typeof AppAuthedSettingsProfileRoute
  '/settings/security': typeof AppAuthedSettingsSecurityRoute
  '/settings/services': typeof AppAuthedSettingsServicesRoute
  '/album/$linkId/$albumId': typeof AppAuthedAlbumLinkIdAlbumIdRoute
  '/artist/$linkId/$artistId': typeof AppAuthedArtistLinkIdArtistIdRoute
  '/playlist/$linkId/$playlistId': typeof AppAuthedPlaylistLinkIdPlaylistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/tv': typeof TvRoute
  '/_app/_authed': typeof AppAuthedRouteWithChildren
  '/_app/design': typeof AppDesignRoute
  '/invite/$code': typeof InviteCodeRoute
  '/join/$token': typeof JoinTokenRoute
  '/_app/_authed/history': typeof AppAuthedHistoryRoute
  '/_app/_authed/me': typeof AppAuthedMeRoute
  '/_app/_authed/room': typeof AppAuthedRoomRoute
  '/_app/_authed/search': typeof AppAuthedSearchRoute
  '/_app/_authed/': typeof AppAuthedIndexRoute
  '/_app/_authed/settings/people': typeof AppAuthedSettingsPeopleRoute
  '/_app/_authed/settings/profile': typeof AppAuthedSettingsProfileRoute
  '/_app/_authed/settings/security': typeof AppAuthedSettingsSecurityRoute
  '/_app/_authed/settings/services': typeof AppAuthedSettingsServicesRoute
  '/_app/_authed/album/$linkId/$albumId': typeof AppAuthedAlbumLinkIdAlbumIdRoute
  '/_app/_authed/artist/$linkId/$artistId': typeof AppAuthedArtistLinkIdArtistIdRoute
  '/_app/_authed/playlist/$linkId/$playlistId': typeof AppAuthedPlaylistLinkIdPlaylistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/tv'
    | '/design'
    | '/invite/$code'
    | '/join/$token'
    | '/history'
    | '/me'
    | '/room'
    | '/search'
    | '/settings/people'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/services'
    | '/album/$linkId/$albumId'
    | '/artist/$linkId/$artistId'
    | '/playlist/$linkId/$playlistId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/tv'
    | '/design'
    | '/invite/$code'
    | '/join/$token'
    | '/history'
    | '/me'
    | '/room'
    | '/search'
    | '/settings/people'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/services'
    | '/album/$linkId/$albumId'
    | '/artist/$linkId/$artistId'
    | '/playlist/$linkId/$playlistId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/tv'
    | '/_app/_authed'
    | '/_app/design'
    | '/invite/$code'
    | '/join/$token'
    | '/_app/_authed/history'
    | '/_app/_authed/me'
    | '/_app/_authed/room'
    | '/_app/_authed/search'
    | '/_app/_authed/'
    | '/_app/_authed/settings/people'
    | '/_app/_authed/settings/profile'
    | '/_app/_authed/settings/security'
    | '/_app/_authed/settings/services'
    | '/_app/_authed/album/$linkId/$albumId'
    | '/_app/_authed/artist/$linkId/$artistId'
    | '/_app/_authed/playlist/$linkId/$playlistId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  TvRoute: typeof TvRoute
  InviteCodeRoute: typeof InviteCodeRoute
  JoinTokenRoute: typeof JoinTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_authed': {
      id: '/_app/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/design': {
      id: '/_app/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof AppDesignRouteImport
      parentRoute: typeof AppRoute
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_authed/': {
      id: '/_app/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppAuthedIndexRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/_app/_authed/history': {
      id: '/_app/_authed/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppAuthedHistoryRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/_app/_authed/me': {
      id: '/_app/_authed/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppAuthedMeRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/_app/_authed/room': {
      id: '/_app/_authed/room'
      path: '/room'
      fullPath: '/room'
      preLoaderRoute: typeof AppAuthedRoomRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/_app/_authed/search': {
      id: '/_app/_authed/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppAuthedSearchRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/_app/_authed/settings/people': {
      id: '/_app/_authed/settings/people'
      path: '/settings/people'
      fullPath: '/settings/people'
      preLoaderRoute: typeof AppAuthedSettingsPeopleRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/_app/_authed/settings/profile': {
      id: '/_app/_authed/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppAuthedSettingsProfileRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/_app/_authed/settings/security': {
      id: '/_app/_authed/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AppAuthedSettingsSecurityRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/_app/_authed/settings/services': {
      id: '/_app/_authed/settings/services'
      path: '/settings/services'
      fullPath: '/settings/services'
      preLoaderRoute: typeof AppAuthedSettingsServicesRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/_app/_authed/album/$linkId/$albumId': {
      id: '/_app/_authed/album/$linkId/$albumId'
      path: '/album/$linkId/$albumId'
      fullPath: '/album/$linkId/$albumId'
      preLoaderRoute: typeof AppAuthedAlbumLinkIdAlbumIdRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/_app/_authed/artist/$linkId/$artistId': {
      id: '/_app/_authed/artist/$linkId/$artistId'
      path: '/artist/$linkId/$artistId'
      fullPath: '/artist/$linkId/$artistId'
      preLoaderRoute: typeof AppAuthedArtistLinkIdArtistIdRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/_app/_authed/playlist/$linkId/$playlistId': {
      id: '/_app/_authed/playlist/$linkId/$playlistId'
      path: '/playlist/$linkId/$playlistId'
      fullPath: '/playlist/$linkId/$playlistId'
      preLoaderRoute: typeof AppAuthedPlaylistLinkIdPlaylistIdRouteImport
      parentRoute: typeof AppAuthedRoute
    }
  }
}

interface AppAuthedRouteChildren {
  AppAuthedHistoryRoute: typeof AppAuthedHistoryRoute
  AppAuthedMeRoute: typeof AppAuthedMeRoute
  AppAuthedRoomRoute: typeof AppAuthedRoomRoute
  AppAuthedSearchRoute: typeof AppAuthedSearchRoute
  AppAuthedIndexRoute: typeof AppAuthedIndexRoute
  AppAuthedSettingsPeopleRoute: typeof AppAuthedSettingsPeopleRoute
  AppAuthedSettingsProfileRoute: typeof AppAuthedSettingsProfileRoute
  AppAuthedSettingsSecurityRoute: typeof AppAuthedSettingsSecurityRoute
  AppAuthedSettingsServicesRoute: typeof AppAuthedSettingsServicesRoute
  AppAuthedAlbumLinkIdAlbumIdRoute: typeof AppAuthedAlbumLinkIdAlbumIdRoute
  AppAuthedArtistLinkIdArtistIdRoute: typeof AppAuthedArtistLinkIdArtistIdRoute
  AppAuthedPlaylistLinkIdPlaylistIdRoute: typeof AppAuthedPlaylistLinkIdPlaylistIdRoute
}

const AppAuthedRouteChildren: AppAuthedRouteChildren = {
  AppAuthedHistoryRoute: AppAuthedHistoryRoute,
  AppAuthedMeRoute: AppAuthedMeRoute,
  AppAuthedRoomRoute: AppAuthedRoomRoute,
  AppAuthedSearchRoute: AppAuthedSearchRoute,
  AppAuthedIndexRoute: AppAuthedIndexRoute,
  AppAuthedSettingsPeopleRoute: AppAuthedSettingsPeopleRoute,
  AppAuthedSettingsProfileRoute: AppAuthedSettingsProfileRoute,
  AppAuthedSettingsSecurityRoute: AppAuthedSettingsSecurityRoute,
  AppAuthedSettingsServicesRoute: AppAuthedSettingsServicesRoute,
  AppAuthedAlbumLinkIdAlbumIdRoute: AppAuthedAlbumLinkIdAlbumIdRoute,
  AppAuthedArtistLinkIdArtistIdRoute: AppAuthedArtistLinkIdArtistIdRoute,
  AppAuthedPlaylistLinkIdPlaylistIdRoute:
    AppAuthedPlaylistLinkIdPlaylistIdRoute,
}

const AppAuthedRouteWithChildren = AppAuthedRoute._addFileChildren(
  AppAuthedRouteChildren,
)

interface AppRouteChildren {
  AppAuthedRoute: typeof AppAuthedRouteWithChildren
  AppDesignRoute: typeof AppDesignRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthedRoute: AppAuthedRouteWithChildren,
  AppDesignRoute: AppDesignRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  TvRoute: TvRoute,
  InviteCodeRoute: InviteCodeRoute,
  JoinTokenRoute: JoinTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
